import LessonEditor from './LessonEditor';
import OwnerPanel from './OwnerPanel';
import StaffInbox from './StaffInbox';
import { downloadCalendar } from './calendar';
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useBravo } from './context';
import { api } from './api';
import { Page, Notice, formatDate, formatTime } from './ui';
import { today } from './BookingPage';
const hours = Array.from({ length: 13 }, (_, i) => `${i + 9}:00`.padStart(5, '0'));
export default function AdminPage() {
  const { user, refreshConfig, authReady } = useBravo();
  const [data, setData] = useState(null), [schedule, setSchedule] = useState(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [query, setQuery] = useState(''), [statusFilter, setStatusFilter] = useState('active'), [visitDate, setVisitDate] = useState('');
  const load = useCallback(async () => { const result = await api('/admin'); setData(result); setSchedule(result.settings); }, []);
  useEffect(() => { if (['staff', 'owner'].includes(user?.role)) load().catch(e => setError(e.message)); }, [user, load]);
  async function action(work) { setBusy(true); setError(''); setNotice(''); try { await work(); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  function toggle(field, value) { setSchedule(s => ({ ...s, [field]: s[field].includes(value) ? s[field].filter(v => v !== value) : [...s[field], value].sort() })); }
  const visible = (data?.bookings || []).filter(b =>
    (statusFilter === 'all' || (statusFilter === 'active' ? b.status !== 'cancelled' : b.status === statusFilter)) &&
    (!visitDate || b.visits.some(v => v.date === visitDate)) &&
    [b.dogName, b.userId?.name, b.userId?.email, b.phone, b._id].some(v => String(v || '').toLowerCase().includes(query.toLowerCase())));
  const agenda = (data?.bookings || []).filter(b => b.status !== 'cancelled').flatMap(b => b.visits.filter(v => v.date === today()).map(v => ({ ...v, booking: b }))).sort((a,b) => a.time.localeCompare(b.time));
  return <Page className="staff-page" title={user?.role === 'owner' ? 'Owner command.' : 'Your day. In order.'} eyebrow={user?.role === 'owner' ? 'BRAVO OWNERSHIP' : 'BRAVO OPERATIONS'} intro="Manage the schedule, client requests, private messages, and online lessons from one desk."><Notice error>{error}</Notice><Notice>{notice}</Notice>{!authReady ? <p role="status">Checking staff access…</p> : !['staff', 'owner'].includes(user?.role) ? <div className="panel"><h2>Bravo staff access required.</h2><p>Staff privileges are assigned by the account owner. Public registration never grants staff access.</p><Link className="button" to="/account">Open your account</Link></div> : !data ? <p role="status">Loading the staff desk…</p> : <>
    <section className="panel"><div className="section-label"><h2>Today’s visits.</h2><button className="quiet-button" disabled={busy} onClick={() => action(async () => {})}>Refresh staff desk</button></div><p className="helper">{formatDate(today())} · Aberdeen time · Requests need your confirmation.</p>{agenda.length ? agenda.map(v => <div className="appointment-line" key={`${v.booking._id}-${v.time}`}><strong>{formatTime(v.time)} · {v.booking.dogName}</strong><span>{v.service} · {v.booking.status}</span><a className="inline-link" href={`tel:${v.booking.phone.replace(/[^+0-9]/g, '')}`}>Call client</a></div>) : <p>No visits scheduled for today.</p>}<div className="record-actions"><a className="inline-link" href="#customer-requests">Review requests</a><a className="inline-link" href="#staff-inbox">Client messages</a><a className="inline-link" href="#lesson-editor">Manage lessons</a>{user.role === 'owner' && <a className="inline-link" href="#owner-controls">People & permissions</a>}<Link className="inline-link" to="/community">Open community</Link></div></section>
    <div className="admin-layout"><section className="panel"><h2>Weekly availability.</h2><p>All times use Aberdeen’s local time. Existing visits stay booked if you change these settings.</p><form onSubmit={e => { e.preventDefault(); action(async () => { await api('/admin/schedule', { method: 'PUT', body: { enabled: schedule.enabled, weekdays: schedule.weekdays, hours: schedule.hours } }); await refreshConfig(); setNotice('Availability updated.'); }); }}><label className="check-label"><input type="checkbox" checked={schedule.enabled} onChange={e => setSchedule(s => ({ ...s, enabled: e.target.checked }))}/>Accept online booking requests</label><fieldset><legend>Working days</legend><div className="check-grid">{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((label,i) => <label className="check-label" key={label}><input type="checkbox" checked={schedule.weekdays.includes(i+1)} onChange={() => toggle('weekdays',i+1)}/>{label}</label>)}</div></fieldset><fieldset><legend>Available starting times</legend><div className="check-grid">{hours.map(time => <label className="check-label" key={time}><input type="checkbox" checked={schedule.hours.includes(time)} onChange={() => toggle('hours',time)}/>{formatTime(time)}</label>)}</div></fieldset><p className="helper">One visit can use each hourly opening. Adjust openings to leave enough travel time between clients.</p><button className="button" disabled={busy}>Save availability</button></form></section>
    <section className="panel"><h2>Block an opening.</h2><form onSubmit={e => { e.preventDefault(); const form = e.currentTarget; action(async () => { await api('/admin/blocks', { method: 'POST', body: Object.fromEntries(new FormData(form)) }); setNotice('Time blocked.'); }); }}><label>Date<input name="date" type="date" min={today()} required/></label><label>Time<select name="time">{hours.map(t => <option key={t} value={t}>{formatTime(t)}</option>)}</select></label><label>Reason<input name="reason" maxLength="200" required placeholder="Travel time, weather, time off…"/></label><button className="button button-ghost" disabled={busy}>Block time</button></form><h3>Blocked times</h3>{data.blocks.length ? data.blocks.map(block => <div className="blocked-time" key={block._id}><p>{formatDate(block.date)} · {formatTime(block.time)}<small>{block.reason}</small></p><button className="quiet-button" disabled={busy} onClick={() => action(() => api(`/admin/blocks/${encodeURIComponent(block._id)}`, { method: 'DELETE', body: {} }))}>Reopen</button></div>) : <p>No blocked openings.</p>}</section></div>
    <section id="customer-requests"><h2>Customer requests.</h2><div className="panel"><div className="form-grid"><label>Search clients or dogs<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Name, email, phone, or booking ID"/></label><label>Status<select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}><option value="active">Active requests & visits</option><option value="requested">Awaiting confirmation</option><option value="confirmed">Confirmed</option><option value="cancelled">Cancelled</option><option value="all">All statuses</option></select></label><label>Visit date<input type="date" value={visitDate} onChange={e => setVisitDate(e.target.value)}/></label></div><button className="quiet-button" onClick={() => { setQuery(''); setStatusFilter('all'); setVisitDate(''); }}>Clear filters</button><p className="helper">Showing {visible.length} of the latest {data.bookings.length} requests.</p></div>{!visible.length ? <div className="panel"><p>No requests match these filters.</p></div> : <div className="admin-bookings">{visible.map(booking => <article className="panel" key={booking._id}><div className="record-top"><span className="badge">{booking.status}</span><span className="badge">{booking.paymentStatus}</span></div><h3>{booking.dogName}</h3><p>{booking.userId?.name} · {booking.userId?.email}</p><p><a className="inline-link" href={`tel:${booking.phone.replace(/[^+0-9]/g, '')}`}>{booking.phone}</a><br/>{booking.address}</p>{booking.notes && <p className="staff-note">{booking.notes}</p>}{booking.visits.map(v => <div className="appointment-line" key={`${v.date}-${v.time}`}><strong>{formatDate(v.date)}</strong><span>{formatTime(v.time)} · {v.service}</span></div>)}{booking.status !== 'cancelled' && <div className="record-actions">{booking.status === 'confirmed' && booking.visits.length > 0 && <button className="quiet-button" onClick={() => downloadCalendar(booking)}>Add to calendar</button>}<Link className="quiet-button" to={`/portal?edit=${booking._id}`}>Change schedule</Link>{booking.status === 'requested' && <button className="button button-small" disabled={busy} onClick={() => action(() => api(`/admin/bookings/${booking._id}`, { method: 'PATCH', body: { status: 'confirmed' } }))}>Confirm visit</button>}<button className="quiet-button" disabled={busy} onClick={() => { if(window.confirm('Cancel this request?')) action(() => api(`/admin/bookings/${booking._id}`, { method: 'PATCH', body: { status: 'cancelled' } })); }}>Cancel request</button>{user.role === 'owner' && booking.paymentStatus === 'paid' && <button className="quiet-button danger-link" disabled={busy} onClick={() => { if(window.confirm('Refund this Stripe payment? This cannot be undone.')) action(() => api(`/admin/bookings/${booking._id}/refund`, { method: 'POST', body: {} })); }}>Issue refund</button>}</div>}</article>)}</div>}</section>
    <StaffInbox inbox={data.inbox}/>
    <LessonEditor/>
    {user.role === 'owner' && <OwnerPanel user={user}/>}
    </>}</Page>;
}
