import { useCallback, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useBravo } from './context';
import { api } from './api';
import { Page, Notice, SetupNotice } from './ui';

const stamp = value => new Date(value).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
function Thread({ messages, empty = 'No messages yet.' }) { return <div className="chat-history panel">{messages.length ? messages.map(message => <article className={`chat-message ${message.kind || 'message'}`} key={message._id}><header><strong>{message.authorName || message.senderName}</strong>{['staff','owner'].includes(message.role || message.senderRole) && <span className="badge">{(message.role || message.senderRole) === 'owner' ? 'OWNER' : 'STAFF'}</span>}<time>{stamp(message.createdAt)}</time></header><p>{message.body}</p></article>) : <div className="empty-state"><h3>Start the conversation.</h3><p>{empty}</p></div>}</div>; }

export default function CommunityPage() {
  const { user, authReady } = useBravo(), [params, setParams] = useSearchParams();
  const tab = params.get('tab') || 'room';
  const [messages, setMessages] = useState([]), [direct, setDirect] = useState([]), [groups, setGroups] = useState([]), [people, setPeople] = useState([]), [activeGroup, setActiveGroup] = useState(null), [groupMessages, setGroupMessages] = useState([]);
  const [body, setBody] = useState(''), [kind, setKind] = useState('message'), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => {
    if (tab === 'room') setMessages((await api('/community')).messages);
    if (tab === 'direct') setDirect((await api('/direct')).messages);
    if (tab === 'groups') { const data = await api('/groups'); setGroups(data.groups); setPeople(data.people); const id = activeGroup?._id || data.groups[0]?._id; if (id) { setActiveGroup(data.groups.find(group => group._id === id)); setGroupMessages((await api(`/groups/${id}/messages`)).messages); } }
  }, [tab, activeGroup?._id]);
  useEffect(() => { if (!user) return; let active = true; const load = () => { if (!document.hidden) refresh().catch(e => active && setError(e.message)); }; load(); const timer = setInterval(load, 10000); return () => { active = false; clearInterval(timer); }; }, [user, refresh]);
  async function send(e) { e.preventDefault(); if (!body.trim()) return; setBusy(true); setError(''); try { const route = tab === 'room' ? '/community' : tab === 'direct' ? '/direct' : `/groups/${activeGroup._id}/messages`; await api(route, { method: 'POST', body: tab === 'room' ? { body, kind } : { body } }); setBody(''); setNotice('Sent.'); await refresh(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function createGroup(e) { e.preventDefault(); const form = new FormData(e.currentTarget); const name = form.get('name'); const members = form.getAll('members'); setBusy(true); try { await api('/groups', { method: 'POST', body: { name, members } }); e.currentTarget.reset(); setNotice('Group created.'); await refresh(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function updateGroup(e) { e.preventDefault(); const members = new FormData(e.currentTarget).getAll('members'); setBusy(true); try { await api(`/groups/${activeGroup._id}`, { method: 'PATCH', body: { members } }); setNotice('Group members updated.'); await refresh(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function hide(id) { if (!window.confirm('Hide this message?')) return; await api(`/community/${id}`, { method: 'DELETE', body: {} }); refresh(); }
  return <Page className="community-page" title="The Bravo community." eyebrow="CONVERSATION, GROUPS & SUPPORT" intro="One clear place for public conversation, private help, and member groups—open around the clock."><SetupNotice/><Notice error>{error}</Notice><Notice>{notice}</Notice>{!authReady ? <p role="status">Checking your account…</p> : !user ? <div className="panel empty-state"><h2>You’re welcome here.</h2><p>Create a profile or sign in to join the conversation.</p><Link className="button" to="/account">Sign in to Bravo</Link></div> : <>
    <nav className="community-tabs" aria-label="Community sections">{[['room','Bravo Room'],['direct','Message Bravo'],['groups','My groups']].map(([id,label]) => <button key={id} aria-pressed={tab === id} onClick={() => { setParams({ tab:id }); setNotice(''); setError(''); }}>{label}</button>)}</nav>
    <div className="community-layout"><section>
      {tab === 'room' && <><Thread messages={messages}/>{['staff','owner'].includes(user.role) && messages.some(Boolean) && <details className="panel"><summary>Moderate recent messages</summary>{messages.slice(-10).map(message => <button className="quiet-button" key={message._id} onClick={() => hide(message._id)}>Hide message from {message.authorName}</button>)}</details>}</>}
      {tab === 'direct' && <><div className="panel thread-intro"><p className="kicker gold">PRIVATE SUPPORT</p><h2>Message the owner or staff.</h2><p>Only you and the Bravo team can see this thread. For urgent needs, call <a href="tel:+16058242767">(605) 824-2767</a>.</p></div><Thread messages={direct} empty="Ask a private question about your account, training, or schedule."/></>}
      {tab === 'groups' && <><div className="group-switcher">{groups.map(group => <button key={group._id} className={activeGroup?._id === group._id ? 'selected' : ''} onClick={async () => { setActiveGroup(group); setGroupMessages((await api(`/groups/${group._id}/messages`)).messages); }}>{group.name}</button>)}</div>{activeGroup ? <Thread messages={groupMessages} empty={`Be the first to post in ${activeGroup.name}.`}/> : <div className="panel empty-state"><h2>Your group space.</h2><p>Create a small group and invite other Bravo members.</p></div>}</>}
      {(tab !== 'groups' || activeGroup) && <form className="panel chat-composer" onSubmit={send}>{tab === 'room' && ['staff','owner'].includes(user.role) && <label>Post type<select value={kind} onChange={e => setKind(e.target.value)}><option value="message">Conversation</option><option value="announcement">Team announcement</option><option value="alert">Urgent alert</option></select></label>}<label>Your message<textarea rows="3" maxLength="1200" required value={body} onChange={e => setBody(e.target.value)} placeholder={tab === 'direct' ? 'How can Bravo help?' : 'Write a useful, respectful message…'}/></label><button className="button button-small" disabled={busy || !body.trim()}>{busy ? 'Sending…' : 'Send message'}</button></form>}
    </section><aside>{tab === 'groups' ? <>{activeGroup && (user.role === 'owner' || activeGroup.ownerId === user.id) && <form className="panel group-members" onSubmit={updateGroup}><p className="kicker gold">GROUP MEMBERS</p><h2>{activeGroup.name}</h2><div className="member-checks">{people.filter(person => person.id !== activeGroup.ownerId).map(person => <label className="check-label" key={person.id}><input type="checkbox" name="members" value={person.id} defaultChecked={activeGroup.members.includes(person.id)}/>{person.name}</label>)}</div><button className="button button-small button-ghost" disabled={busy}>Update members</button></form>}<form className="panel" onSubmit={createGroup}><p className="kicker gold">NEW GROUP</p><h2>Bring people together.</h2><label>Group name<input name="name" minLength="2" maxLength="60" required/></label><div className="member-checks">{people.filter(person => person.id !== user.id).map(person => <label className="check-label" key={person.id}><input type="checkbox" name="members" value={person.id}/>{person.name}</label>)}</div><p className="helper">Choose the people you want in this group. You can change members later.</p><button className="button button-ghost" disabled={busy}>Create group</button></form></> : <section className="panel prose"><h3>Simple community rules.</h3><p>Be useful, be respectful, and keep addresses, passwords, payment details, and medical records private.</p><p>The owner can mute or block accounts when needed. This space is available 24/7 but is not monitored continuously.</p></section>}</aside></div>
  </>}</Page>;
}
