import MembershipTerms from './MembershipTerms';
import { downloadCalendar } from './calendar';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useSearchParams, useNavigate } from 'react-router-dom';
import { useBravo } from './context';
import { api } from './api';
import { Page, Notice, SetupNotice, AppointmentNotice, formatDate, formatTime } from './ui';
import { ALL_SERVICES, SERVICES, money } from '../../shared/catalog';
import { accessLabel, deskLabel } from '../../shared/access';
const serviceName = id => ALL_SERVICES.find(service => service.id === id)?.name || 'Legacy Bravo program';
const isBookable = booking => booking.serviceIds.every(id => SERVICES.some(service => service.id === id));
export default function AccountPage() {
  const { user, config, refreshUser, authReady, setBookingDraft } = useBravo(), [params] = useSearchParams(), navigate = useNavigate();
  const returningBooking = params.get('booking');
  const loadSequence = useRef(0);
  const [resetVersion, setResetVersion] = useState(0);
  const [mode, setMode] = useState('login'), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [bookings, setBookings] = useState([]), [subscriptions, setSubscriptions] = useState([]), [loading, setLoading] = useState(false), [verificationDelayed, setVerificationDelayed] = useState(false);
  const [membershipAccess, setMembershipAccess] = useState({ active: false, manual: false, onlineAccess: false });
  const returnedStatus = bookings.find(booking => booking._id === returningBooking)?.paymentStatus;
  const verifying = params.get('payment') === 'verifying' && !['paid', 'covered', 'review', 'refunded'].includes(returnedStatus);
  const [review, setReview] = useState({ rating: 5, body: '' });
  const [profile, setProfile] = useState({ name: '', dogName: '', phone: '', address: '', title: '', bio: '', showPhone: false });
  const load = useCallback(async () => {
    if (!user || user.mustChangePassword) return;
    const ticket = ++loadSequence.current;
    const [records, membership, feedback] = await Promise.all([api('/bookings'), api('/auth/me'), api('/reviews/mine')]);
    if (ticket !== loadSequence.current) return;
    setBookings(records.bookings.map(booking => booking.status === 'waitlisted' ? { ...booking, stripeSessionId: booking.stripeSessionId || 'trainer-waitlist' } : booking)); setSubscriptions(membership.subscriptions); setMembershipAccess(membership.membership || { active: false, manual: false, onlineAccess: false }); setReview(feedback.review ? { rating: feedback.review.rating, body: feedback.review.body } : { rating: 5, body: '' });
  }, [user]);
  useEffect(() => { if (user && !user.mustChangePassword) { setLoading(true); load().catch(e => setError(e.message)).finally(() => setLoading(false)); setProfile({ name: user.name, dogName: user.dogName || '', phone: user.phone || '', address: user.address || '', title: user.title || '', bio: user.bio || '', showPhone: !!user.showPhone }); } }, [user, load]);
  useEffect(() => {
    if (!verifying || !user) return;
    let ticks = 0;
    const timer = setInterval(() => { if (++ticks > 12) { setVerificationDelayed(true); return clearInterval(timer); } load().catch(() => {}); }, 5000);
    return () => clearInterval(timer);
  }, [verifying, user, load]);
  async function action(work) { setBusy(true); setError(''); setNotice(''); try { await work(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function resetAccount() {
    if (!window.confirm('Discard unsaved profile, review and password inputs, clear your unsaved booking plan, and reload fresh account data? Saved bookings, memberships, reviews and profile information will not be deleted.')) return;
    await action(async () => {
      loadSequence.current++;
      setBookingDraft(null); setResetVersion(value => value + 1);
      setReview({ rating: 5, body: '' });
      setProfile({ name: user.name, dogName: user.dogName || '', phone: user.phone || '', address: user.address || '', title: user.title || '', bio: user.bio || '', showPhone: !!user.showPhone });
      await Promise.all([refreshUser(), load()]);
      setNotice('Account inputs and unsaved booking selections reset. Saved records reloaded without browser cache.');
    });
  }
  function openBilling() { action(async () => { const result = await api('/billing/portal', { method: 'POST', body: {} }); window.location.assign(result.url); }); }
  function authenticate(event) { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); action(async () => { const result = await api(`/auth/${mode}`, { method: 'POST', body: form }); await refreshUser(); const next = params.get('next'); if (!result.user.mustChangePassword && next && /^\/portal(?:\?[^#]*)?$/.test(next)) navigate(next); }); }
  function cancel(id) { if (!window.confirm('Cancel this booking? This does not refund payments. Your paid membership keeps its recorded end date.')) return; action(async () => { const result = await api(`/bookings/${id}/cancel`, { method: 'POST', body: {} }); setNotice(result.message); await load(); }); }
  return <Page title={user ? `Welcome, ${user.name.split(' ')[0]}.` : 'Your Bravo account.'} className="account-page" eyebrow="YOUR BRAVO" intro={user ? 'Your bookings, care details, and memberships—all together.' : 'Sign in to save appointments, manage your program, and join the Bravo Room.'}>
    <SetupNotice/><Notice error>{error}</Notice><Notice>{notice}</Notice>
    {!authReady ? <p role="status">Checking your account…</p> : !user ? <div className="account-auth panel"><div className="tab-row"><button aria-pressed={mode === 'login'} onClick={() => setMode('login')}>Sign in</button><button aria-pressed={mode === 'register'} onClick={() => setMode('register')}>Create account</button></div><form onSubmit={authenticate}><div className="auth-heading"><h2>{mode === 'register' ? 'Meet your Bravo team.' : 'Good to have you back.'}</h2><p>{mode === 'register' ? 'One account for your visits, care details, and the Bravo Room. Already a Bravo customer? Create your account and ask the team to activate your Member access.' : 'Sign in to pick up where you left off.'}</p></div>{mode === 'register' && <label>Your name<input name="name" autoComplete="name" minLength="2" maxLength="80" required/></label>}<label>{mode === 'register' ? 'Email' : 'Name or email'}<input key={mode} name={mode === 'register' ? 'email' : 'identifier'} type={mode === 'register' ? 'email' : 'text'} autoComplete={mode === 'register' ? 'email' : 'username'} maxLength="254" required/></label><label>Password<input name="password" type="password" autoComplete={mode === 'register' ? 'new-password' : 'current-password'} minLength="12" maxLength="128" required/></label><p className="helper">Use at least 12 characters to keep your account secure.</p><button className="button" disabled={busy || !config?.connected}>{busy ? 'Please wait…' : mode === 'register' ? 'Create my account' : 'Sign in'}</button><p className="helper">Need account recovery? <a href="tel:+16058242767">Contact Bravo</a> to verify your identity.</p></form></div> : <>
    <div className="account-role-line"><span className="badge">{user.role === 'member' && membershipAccess.active ? 'MEMBER' : accessLabel(user).toUpperCase()}</span>{['staff','owner'].includes(user.role) && <Link className="inline-link" to="/admin">Open {deskLabel(user)} →</Link>}</div><div className="account-actions"><Link className="button" to="/schedule">My schedule</Link><Link className="button button-ghost" to="/portal?new=1">New service request</Link><Link className="button button-ghost" to="/learn">Member lessons</Link><Link className="button button-ghost" to="/community?tab=direct">Message Bravo</Link>{user.role === 'owner' && <Link className="button button-ghost" to="/admin#owner-controls">Manage Members</Link>}</div>
    {params.get('payment') === 'verifying' && <Notice>{returnedStatus === 'paid' ? 'Stripe has confirmed your payment. Your request still follows Bravo’s visit-confirmation process.' : returnedStatus === 'covered' ? 'Your membership covers this request.' : returnedStatus === 'refunded' ? 'The refund is confirmed.' : returnedStatus === 'review' ? 'Your payment needs staff review. Do not pay again; contact Bravo.' : verificationDelayed ? 'Confirmation is taking longer than expected. Do not create another payment. Refresh your account later or contact Bravo.' : 'We’re checking payment confirmation with Stripe. Returning here alone does not confirm payment.'}</Notice>}
    {params.get('payment') === 'cancelled' && <Notice>You left checkout. Your saved request is still here, and payment has not been assumed.</Notice>}
    <MembershipTerms/><AppointmentNotice/><div className="account-layout"><section><div className="section-label"><h2>Your requests & visits</h2><button className="quiet-button" disabled={busy} onClick={resetAccount}>Refresh & reset inputs</button></div>{loading ? <p role="status">Loading requests…</p> : bookings.length === 0 ? <div className="panel empty-state"><h3>A good place to start.</h3><p>No bookings yet. Choose a program and find the days you need us.</p><Link className="inline-link" to="/portal">Choose a program →</Link></div> : bookings.map(booking => <article className={`panel booking-record ${returningBooking === booking._id ? 'payment-return-record' : ''}`} key={booking._id}><div className="record-top"><span className={`badge ${booking.status}`}>{booking.status}</span><span className="badge">{booking.paymentStatus === 'covered' ? 'Membership covered' : booking.paymentStatus === 'refunded' ? 'Refunded' : booking.paymentStatus === 'paid' ? 'Paid' : booking.paymentStatus === 'review' ? 'Payment needs staff review' : 'Not paid'}</span><small>#{booking._id.slice(-6)}</small></div><h3>{booking.serviceIds.map(serviceName).join(' + ')}</h3><p>For {booking.dogName}{booking.serviceIds.some(id => ['training', 'walking'].includes(id)) ? ` · ${booking.dogCount || 1} ${(booking.dogCount || 1) === 1 ? 'dog' : 'dogs'}` : ''}{booking.serviceIds.includes('walking') ? ' · 30-minute walk' : ''}</p>{booking.visits.map(v => <div className="appointment-line" key={`${v.date}-${v.time}`}><strong>{formatDate(v.date)}</strong><span>{formatTime(v.time)} · {v.service}</span></div>)}<p className="helper">{booking.quote.monthlyCents > 0 ? `${money(booking.quote.monthlyCents)}/month` : ''}{booking.quote.oneTimeCents > 0 ? `${booking.quote.monthlyCents > 0 ? ' + ' : ''}${money(booking.quote.oneTimeCents)} scheduled services` : ''}</p>{!isBookable(booking) && <p className="helper">This retired service is preserved in your account history. Contact Bravo for assistance.</p>}{booking.status !== 'cancelled' && <div className="record-actions">{booking.status === 'confirmed' && booking.visits.length > 0 && <button className="quiet-button" onClick={() => downloadCalendar(booking)}>Add visits to calendar</button>}{isBookable(booking) && booking.paymentStatus === 'unpaid' && config?.paymentsReady && <button className="button button-small checkout-record-button" disabled={busy || !config?.paymentsReady} onClick={() => action(async () => { const result = await api(`/bookings/${booking._id}/checkout`, { method: 'POST', body: {} }); window.location.assign(result.url); })}>Secure checkout · {money(booking.quote?.dueNowCents || 0)}</button>}{isBookable(booking) && !booking.stripeSessionId && booking.visits.length > 0 && <Link className="inline-link" to={`/portal?edit=${booking._id}`}>Change visits</Link>}<button className="quiet-button" disabled={busy} onClick={() => cancel(booking._id)}>Cancel request</button></div>}</article>)}</section>
    <aside><section className="panel"><h2>Payment methods & billing</h2><p>Review your payment details through Stripe’s secure portal.</p>{user.hasBillingAccount && config?.paymentsReady && <button className="button button-ghost" disabled={busy} onClick={openBilling}>Manage secure billing</button>}</section>
    <section className="panel"><h2>Your details.</h2><form onSubmit={e => { e.preventDefault(); action(async () => { await api('/auth/profile', { method: 'PATCH', body: profile }); await refreshUser(); setNotice('Your profile is saved.'); }); }}><label>Your name<input value={profile.name} autoComplete="name" required onChange={e => setProfile(p => ({ ...p, name: e.target.value }))}/></label><label>Dog’s name<input value={profile.dogName} autoComplete="off" onChange={e => setProfile(p => ({ ...p, dogName: e.target.value }))}/></label><label>Phone<input value={profile.phone} type="tel" autoComplete="tel" onChange={e => setProfile(p => ({ ...p, phone: e.target.value }))}/></label><label>Visit address<input value={profile.address} autoComplete="street-address" onChange={e => setProfile(p => ({ ...p, address: e.target.value }))}/></label>{['staff','owner'].includes(user.role) && <><label>Public trainer title<input value={profile.title} onChange={e => setProfile(p => ({ ...p, title: e.target.value }))}/></label><label>Public trainer bio<textarea rows="3" value={profile.bio} onChange={e => setProfile(p => ({ ...p, bio: e.target.value }))}/></label><label className="check-label"><input type="checkbox" checked={profile.showPhone} onChange={e => setProfile(p => ({ ...p, showPhone: e.target.checked }))}/>Show my phone on Call a Trainer</label></>}<button className="button button-ghost" disabled={busy}>Save profile</button></form></section>
    <section className="panel" id="your-review"><h2>Your review.</h2><p>Share one honest review tied to your Bravo account. You can update it later.</p><form onSubmit={e => { e.preventDefault(); action(async () => { const result = await api('/reviews/mine', { method: 'PUT', body: review }); setNotice(result.review.hidden ? 'Your changes are saved. This review remains hidden pending staff review.' : 'Your review is published. Thank you.'); }); }}><label>Star rating<select value={review.rating} onChange={e => setReview(r => ({ ...r, rating: Number(e.target.value) }))}>{[5,4,3,2,1].map(value => <option key={value} value={value}>{value} {value === 1 ? 'star' : 'stars'}</option>)}</select></label><label>Written review<textarea rows="4" minLength="10" maxLength="1200" required value={review.body} onChange={e => setReview(r => ({ ...r, body: e.target.value }))}/></label><button className="button button-ghost" disabled={busy || review.body.trim().length < 10}>Publish review</button></form></section>
    <details className="panel" key={`password-${resetVersion}`}><summary>Change password</summary><form onSubmit={e => { e.preventDefault(); const form = e.currentTarget; action(async () => { await api('/auth/password', { method: 'POST', body: Object.fromEntries(new FormData(form)) }); form.reset(); setNotice('Password updated. Other sessions have been signed out.'); }); }}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label>New password<input name="password" type="password" autoComplete="new-password" minLength="12" maxLength="128" required/></label><button className="button" disabled={busy}>Update password</button></form></details></aside></div></>}
  </Page>;
}
