import { Editable } from './SiteContent';
import SiteHealth from './SiteHealth';
import { trainerOptions, trainerChoice, bookingTrainerIds } from '../../shared/trainers';
import WeekendSessions from './WeekendSessions';
import TrainerClients from './TrainerClients';
import LessonEditor from './LessonEditor';
import OwnerPanel from './OwnerPanel';
import StaffInbox from './StaffInbox';
import StaffBooking from './StaffBooking';
import StaffDayCredits from './StaffDayCredits';
import StaffScheduleEditor from './StaffScheduleEditor';
import ClientDirectory from './ClientDirectory';
import './trainer-schedules.css';
import { downloadCalendar } from './calendar';
import { useCallback, useEffect, useState } from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import { useBravo } from './context';
import { api } from './api';
import ActionFeedback from './ActionFeedback';
import { Page, Notice, AppointmentNotice, formatDate, formatTime } from './ui';
import { today } from './BookingPage';
import { ALL_SERVICES, money } from '../../shared/catalog';
import { deskLabel } from '../../shared/access';

const hours = Array.from({ length: 13 }, (_, i) => `${i + 9}:00`.padStart(5, '0'));
const serviceName = id => ALL_SERVICES.find(service => service.id === id)?.name || 'Legacy Bravo program';
export default function AdminPage() {
  const { notifications, user, config, refreshConfig, authReady, setBookingDraft } = useBravo();
  const [data, setData] = useState(null), [schedule, setSchedule] = useState(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [loadFailed, setLoadFailed] = useState(false);
  const [resetVersion, setResetVersion] = useState(0);
  const [tab, setTab] = useState(() => new URLSearchParams(window.location.search).get('tab') || 'schedule'), [query, setQuery] = useState(''), [statusFilter, setStatusFilter] = useState('active'), [visitDate, setVisitDate] = useState(''), [trainer, setTrainer] = useState('all');
  const location = useLocation(), navigate = useNavigate();
  useEffect(() => { const wanted = new URLSearchParams(location.search).get('tab') || 'schedule'; if ( ['schedule', 'people', 'messages', 'lessons', 'services', 'reviews', 'health'].includes(wanted)) setTab(wanted); }, [location.search]);
  const load = useCallback(async () => { setLoadFailed(false); try { const result = await api('/admin'); const [reviews, services] = result.role === 'owner' ? await Promise.all([api('/admin/reviews').then(data => data.reviews), api('/admin/services').then(data => data.services)]) : [[], []]; setData({ ...result, reviews, services }); setSchedule(result.settings); } catch (error) { setLoadFailed(true); throw error; } }, []);
  useEffect(() => { if (['staff', 'owner'].includes(user?.role)) load().catch(e => setError(e.message)); }, [user, load]);
  useEffect(() => { if (tab !== 'messages') return; const timer = setInterval(() => { if (!document.hidden) load().catch(e => setError(e.message)); }, 15000); load().catch(e => setError(e.message)); return () => clearInterval(timer); }, [tab, location.search, load]);
  async function action(work) { setBusy(true); setError(''); setNotice(''); try { await work(); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function resetDesk() {
    if (!window.confirm('Clear unsaved desk selections, filters and forms, then reload fresh server data? Saved bookings, client accounts, messages and payments will not be deleted. Use the labelled chat controls to clear history.')) return;
    setBusy(true); setError(''); setNotice('');
    setQuery(''); setStatusFilter('active'); setVisitDate(''); setTrainer('all'); setBookingDraft(null);
    try { await Promise.all([load(), refreshConfig()]); setResetVersion(value => value + 1); setNotice('Unsaved forms and filters cleared. Your saved desk information is up to date.'); }
    catch (err) { setError(err.message); } finally { setBusy(false); }
  }
  function toggle(field, value) { setSchedule(s => ({ ...s, [field]: s[field].includes(value) ? s[field].filter(v => v !== value) : [...s[field], value].sort() })); }
  const mine = b => trainer === 'all' || (trainer === 'unassigned' ? !bookingTrainerIds(b).length : bookingTrainerIds(b).includes(trainer));
  const visible = (data?.bookings || []).filter(b => mine(b) &&
    (statusFilter === 'all' || (statusFilter === 'active' ? b.status !== 'cancelled' : b.status === statusFilter)) &&
    (!visitDate || b.visits.some(v => v.date === visitDate)) &&
    [b.dogName, b.userId?.name, b.userId?.email, b.phone, b._id].some(v => String(v || '').toLowerCase().includes(query.toLowerCase())));
  const agenda = (data?.bookings || []).filter(b => mine(b) && !['cancelled', 'waitlisted'].includes(b.status)).flatMap(b => b.visits.filter(v => v.date === today()).map(v => ({ ...v, booking: b }))).sort((a,b) => a.time.localeCompare(b.time));
  const allowed = ['staff', 'owner'].includes(user?.role);
  function goToTask(id) { const target = document.getElementById(id); if (!target) return; if (target.tagName === 'DETAILS') target.open = true; target.scrollIntoView({ behavior: 'instant', block: 'start' }); const focus = target.querySelector('summary, input, select, h2'); if (focus) { if (focus.tagName === 'H2') focus.tabIndex = -1; focus.focus({ preventScroll: true }); } }
  const tabs = [...(user?.isPrimaryOwner ? [['health', 'Website health']] : []), ['schedule', 'Schedule'], ['lessons', 'Lesson studio'], ['messages', 'Messages'], ...(user?.role === 'owner' ? [['people', 'People & access'], ['services', 'Services & pricing'], ['reviews', 'Reviews']] : user?.role === 'staff' ? [['people', 'People & access']] : [])];
  return <Page className="staff-page" title={`Your ${deskLabel(user).toLowerCase()}.`} eyebrow={user?.isPrimaryOwner ? 'BRAVO OWNERSHIP' : 'BRAVO OPERATIONS'} intro="Choose a task. Keep your day, your clients, and your lessons in one place.">
    <ActionFeedback error={error} notice={notice} onDismiss={() => { setError(''); setNotice(''); }}/>{allowed && <Editable as="div" contentKey="adminpage-1" className="reset-actions desk-reset"><Editable as="button" contentKey="adminpage-2" canEditText className="button button-small button-ghost" type="button" disabled={busy} onClick={resetDesk}>Refresh & reset desk</Editable><Editable as="small" contentKey="adminpage-3" canEditText>Clear unsaved forms and selections; keep saved records.</Editable></Editable>}
    {!authReady ? <Editable as="p" contentKey="adminpage-4" canEditText role="status">Checking access…</Editable> : !allowed ? <Editable as="div" contentKey="adminpage-5" className="panel"><Editable as="h2" contentKey="adminpage-6" canEditText>Team access required.</Editable><Editable as="p" contentKey="adminpage-7" canEditText>The owner assigns staff privileges to registered accounts.</Editable><Editable as={Link} contentKey="adminpage-8" canEditLink canEditText className="button" to="/account">Open your account</Editable></Editable> : !data ? loadFailed ? <Editable as="div" contentKey="adminpage-9" className="panel"><Editable as="p" contentKey="adminpage-10" canEditText>Your desk couldn’t load. Try again to get the latest records.</Editable><Editable as="button" contentKey="adminpage-11" canEditText type="button" className="button button-ghost" disabled={busy} onClick={() => action(async () => {})}>Try again</Editable></Editable> : <Editable as="p" contentKey="adminpage-12" canEditText role="status">Loading your desk…</Editable> : <>
      <Editable as="nav" contentKey="adminpage-13" className="community-tabs desk-tabs" aria-label="Desk sections">{tabs.map(([id, label]) => <Editable as="button" contentKey="adminpage-14" key={id} aria-pressed={tab === id} onClick={() => { setTab(id); const next = new URLSearchParams(location.search); next.set('tab', id); if (id !== tab) navigate({ pathname: '/admin', search: next.toString() }); setError(''); setNotice(''); }}>{label}{id === 'messages' && (notifications || []).some(item=>item.unread&&item.id.startsWith('message:')) && <Editable as="span" contentKey="adminpage-15" className="notification-count">{(notifications || []).filter(item => item.unread && item.id.startsWith('message:')).length}</Editable>}</Editable>)}</Editable>
      <Editable as="p" contentKey="adminpage-16" className="desk-section-description">{{schedule: 'Today’s visits, client calendars, and trainer availability.', people: 'Find a client, manage membership, or help them sign in.', messages: 'Read and reply to client messages.', lessons: 'Manage the lessons available to members.', services: 'Manage the programs clients can request.', reviews: 'Review customer feedback.'}[tab]}</Editable>
      {tab === 'health' && user.isPrimaryOwner && <SiteHealth/>}
      {tab === 'schedule' && <>
        <Editable as="nav" contentKey="adminpage-17" className="schedule-shortcuts" aria-label="Schedule shortcuts"><Editable as={Link} contentKey="adminpage-18" canEditLink canEditText to="/admin?tab=people">Find a client</Editable><Editable as="button" contentKey="adminpage-19" canEditText type="button" onClick={() => goToTask('credit-client-days')}>Credit days</Editable><Editable as="button" contentKey="adminpage-20" canEditText type="button" onClick={() => goToTask('my-working-schedule')}>My working hours</Editable><Editable as="button" contentKey="adminpage-21" canEditText type="button" onClick={() => goToTask('customer-requests')}>Requests &amp; visits</Editable></Editable>
        <AppointmentNotice compact/>
        <Editable as="section" contentKey="adminpage-22" className="panel"><Editable as="div" contentKey="adminpage-23" className="section-label"><Editable as="h2" contentKey="adminpage-24" canEditText>Today’s visits.</Editable><Editable as="button" contentKey="adminpage-25" canEditText className="quiet-button" disabled={busy} onClick={resetDesk}>Refresh & reset</Editable></Editable>
          <Editable as="div" contentKey="adminpage-26" className="form-grid"><Editable as="p" contentKey="adminpage-27">{formatDate(today())} · Aberdeen time</Editable><Editable as="label" contentKey="adminpage-28">View schedule<select value={trainer} onChange={e => setTrainer(e.target.value)}><option value="all">Whole team</option><option value={user.id}>My visits</option><option value="unassigned">Unassigned visits</option>{data.team.filter(person => person._id !== user.id).map(person => <option key={person._id} value={person._id}>{person.name}</option>)}</select></Editable></Editable>
          {agenda.length ? agenda.map(v => <Editable as="div" contentKey="adminpage-29" className="appointment-line" key={`${v.booking._id}-${v.time}`}><Editable as="strong" contentKey="adminpage-30">{formatTime(v.time)} · {v.booking.dogName}</Editable><Editable as="span" contentKey="adminpage-31">{v.booking.userId?.name} · {v.booking.status}</Editable>{v.booking.phone && <Editable as="a" contentKey="adminpage-32" canEditText className="inline-link" href={`tel:${v.booking.phone.replace(/[^+0-9]/g, '')}`}>Call client</Editable>}{v.booking.userId?._id && <Editable as={Link} contentKey="adminpage-33" canEditText className="inline-link" to={`/schedule?client=${v.booking.userId._id}`}>View schedule</Editable>}</Editable>) : <Editable as="p" contentKey="adminpage-34" canEditText>No visits today for this view.</Editable>}
          <Editable as="p" contentKey="adminpage-35" canEditText className="helper">Requests need confirmation. Openings follow each assigned trainer’s working hours and saved visits.</Editable>
        </Editable>
        <TrainerClients key={`clients-${resetVersion}`} staffId={user.id}/><WeekendSessions/><StaffDayCredits key={`credits-${resetVersion}`}/><StaffScheduleEditor key={`personal-schedule-${resetVersion}`} team={data.team}/><StaffBooking key={`booking-${resetVersion}`} team={data.team} onSaved={load}/>
        <Editable as="section" contentKey="adminpage-36" id="customer-requests"><Editable as="h2" contentKey="adminpage-37" canEditText>Requests & upcoming visits.</Editable>
          <Editable as="div" contentKey="adminpage-38" className="panel"><Editable as="div" contentKey="adminpage-39" className="form-grid"><Editable as="label" contentKey="adminpage-40">Find a client or dog<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Name, email, phone, or booking ID"/></Editable><Editable as="label" contentKey="adminpage-41">Status<select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}><option value="active">Active requests, waitlist & visits</option><option value="waitlisted">Trainer waiting list</option><option value="requested">Awaiting confirmation</option><option value="confirmed">Confirmed</option><option value="cancelled">Cancelled</option><option value="all">All statuses</option></select></Editable><Editable as="label" contentKey="adminpage-42">Visit date<input type="date" value={visitDate} onChange={e => setVisitDate(e.target.value)}/></Editable></Editable><Editable as="button" contentKey="adminpage-43" canEditText type="button" className="quiet-button" onClick={() => { setQuery(''); setStatusFilter('active'); setVisitDate(''); setTrainer('all'); }}>Reset filters</Editable><Editable as="p" contentKey="adminpage-44" className="helper">Showing {visible.length} of the latest {data.bookings.length} requests.</Editable></Editable>
          {!visible.length ? <Editable as="div" contentKey="adminpage-45" className="panel"><Editable as="p" contentKey="adminpage-46" canEditText>No requests match this view.</Editable></Editable> : <Editable as="div" contentKey="adminpage-47" className="admin-bookings">{visible.map(booking => <Editable as="article" contentKey="adminpage-48" className="panel" key={booking._id}>
            <Editable as="div" contentKey="adminpage-49" className="record-top"><Editable as="span" contentKey="adminpage-50" className="badge">{booking.status}</Editable><Editable as="span" contentKey="adminpage-51" className="badge">{booking.paymentStatus}</Editable></Editable><Editable as="h3" contentKey="adminpage-52">{booking.dogName}</Editable><Editable as="p" contentKey="adminpage-53">{booking.serviceIds.map(serviceName).join(' + ')}{booking.serviceIds.some(id => ['training', 'walking'].includes(id)) ? ` · ${booking.dogCount || 1} ${(booking.dogCount || 1) === 1 ? 'dog' : 'dogs'}` : ''} · {money(booking.quote?.dueNowCents || 0)} due</Editable><Editable as="p" contentKey="adminpage-54">{booking.userId?.name || 'Former client'} · {booking.userId?.email}</Editable><Editable as="p" contentKey="adminpage-55"><Editable as="a" contentKey="adminpage-56" className="inline-link" href={`tel:${booking.phone.replace(/[^+0-9]/g, '')}`}>{booking.phone}</Editable><br/>{booking.address}</Editable>{booking.notes && <Editable as="p" contentKey="adminpage-57" className="staff-note">{booking.notes}</Editable>}
            {booking.userId?._id && <Editable as={Link} contentKey="adminpage-58" canEditText className="button button-small" to={`/schedule?client=${booking.userId._id}`}>Client schedule & PDF</Editable>}
            {booking.status === 'waitlisted' && <Notice>Waiting-list request. These are preferred dates only and are not reserved. Choose a trainer below to activate it when capacity and the requested times are available.</Notice>}
            {booking.visits.map(v => <Editable as="div" contentKey="adminpage-59" className="appointment-line" key={`${v.date}-${v.time}`}><Editable as="strong" contentKey="adminpage-60">{formatDate(v.date)}</Editable><Editable as="span" contentKey="adminpage-61">{formatTime(v.time)} · {v.service}</Editable></Editable>)}
            {booking.trainerAcceptanceRequired&&<Editable as="p" contentKey="adminpage-62" canEditText className="helper">Awaiting trainer acceptance. Open Training clients above or the trainer’s profile to accept.</Editable>}<Editable as="label" contentKey="adminpage-63">{booking.status === 'waitlisted' ? 'Preferred trainer / activate request' : 'Assigned trainer'}<select disabled={busy || booking.status === 'cancelled'} value={booking.staffId ? trainerChoice(booking) : ''} onChange={e => { const staffId = e.target.value || null; action(async () => { await api(`/admin/bookings/${booking._id}/assignment`, { method: 'PATCH', body: { staffId } }); setNotice('Trainer assignment saved.'); }); }}><option value="">{booking.requestedStaffId ? `Waiting for ${trainerOptions(data.team).find(person => person._id === trainerChoice(booking))?.name || 'chosen trainer'}` : 'Unassigned'}</option>{booking.staffId && !data.team.some(person => person._id === booking.staffId) && <option value={booking.staffId}>Former staff — reassign this visit</option>}{trainerOptions(data.team).map(person => <option key={person._id} value={person._id} disabled={person.disabled}>{person.name}</option>)}</select></Editable>
            {booking.status !== 'cancelled' && <Editable as="div" contentKey="adminpage-64" className="record-actions">{booking.status === 'confirmed' && booking.visits.length > 0 && <Editable as="button" contentKey="adminpage-65" canEditText className="quiet-button" onClick={() => downloadCalendar(booking)}>Add to calendar</Editable>}
              {booking.visits.length > 0 && !booking.stripeSessionId && <Editable as={Link} contentKey="adminpage-66" canEditText className="quiet-button" to={`/portal?edit=${booking._id}`}>Change dates or times</Editable>}
              {booking.status === 'requested' && <Editable as="button" contentKey="adminpage-67" canEditText className="button button-small" disabled={busy} onClick={() => action(async () => { await api(`/admin/bookings/${booking._id}`, { method: 'PATCH', body: { status: 'confirmed' } }); setNotice('Visit confirmed.'); })}>Confirm visit</Editable>}
              <Editable as="button" contentKey="adminpage-68" canEditText className="quiet-button" disabled={busy} onClick={() => { if(window.confirm('Cancel this visit? This does not refund a payment.')) action(async () => { await api(`/admin/bookings/${booking._id}`, { method: 'PATCH', body: { status: 'cancelled' } }); setNotice('Visit cancelled.'); }); }}>Cancel visit</Editable>
            </Editable>}
            {user.role === 'owner' && ['paid', 'review'].includes(booking.paymentStatus) && (config?.paymentsReady ? <Editable as="button" contentKey="adminpage-69" className="quiet-button danger-link" disabled={busy} onClick={() => { if (window.confirm(`Issue the verified ${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((booking.quote?.dueNowCents || 0)/100)} refund through Stripe? This cannot be undone here.`)) action(async () => { const result = await api(`/admin/bookings/${booking._id}/refund`, { method: 'POST', body: {} }); setNotice(result.message); }); }}>{booking.refundId ? 'Check Stripe refund' : 'Issue Stripe refund'}</Editable> : <Editable as="p" contentKey="adminpage-70" canEditText className="helper">Refund control will activate only after verified Stripe setup is enabled.</Editable>)}
          </Editable>)}</Editable>}
        </Editable>
        <Editable as="details" contentKey="adminpage-71" className="panel" key={`availability-${resetVersion}`}><Editable as="summary" contentKey="adminpage-72" canEditText>Shared team calendar & closures</Editable><Editable as="p" contentKey="adminpage-73" canEditText>These settings apply to the shared team calendar. Existing visits stay booked.</Editable><Editable as="div" contentKey="adminpage-74" className="admin-layout">
          <Editable as="section" contentKey="adminpage-75"><Editable as="h3" contentKey="adminpage-76" canEditText>Weekly availability</Editable><form onSubmit={e => { e.preventDefault(); action(async () => { await api('/admin/schedule', { method: 'PUT', body: { enabled: schedule.enabled, weekdays: schedule.weekdays, hours: schedule.hours } }); await refreshConfig(); setNotice('Availability updated.'); }); }}><Editable as="label" contentKey="adminpage-77" className="check-label"><input type="checkbox" checked={schedule.enabled} onChange={e => setSchedule(s => ({ ...s, enabled: e.target.checked }))}/>Accept online booking requests</Editable><fieldset><legend>Working days</legend><Editable as="div" contentKey="adminpage-78" className="check-grid">{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((label,i) => <Editable as="label" contentKey="adminpage-79" className="check-label" key={label}><input type="checkbox" disabled={i >= 5 && user.role !== 'owner'} checked={schedule.weekdays.includes(i+1)} onChange={() => toggle('weekdays',i+1)}/>{label}</Editable>)}</Editable></fieldset><fieldset><legend>Starting times</legend><Editable as="div" contentKey="adminpage-80" className="check-grid">{hours.map(time => <Editable as="label" contentKey="adminpage-81" className="check-label" key={time}><input type="checkbox" checked={schedule.hours.includes(time)} onChange={() => toggle('hours',time)}/>{formatTime(time)}</Editable>)}</Editable></fieldset><Editable as="div" contentKey="adminpage-82" className="reset-actions"><Editable as="button" contentKey="adminpage-83" canEditText className="button" disabled={busy}>Save availability</Editable><Editable as="button" contentKey="adminpage-84" canEditText type="button" className="quiet-button" disabled={busy} onClick={() => { setSchedule(current => ({ ...current, weekdays: [], hours: [] })); setNotice('Availability selections cleared locally. Choose the new days and times before saving. Existing appointments were not changed.'); }}>Reset availability selections</Editable></Editable></form></Editable>
          <Editable as="section" contentKey="adminpage-85"><Editable as="h3" contentKey="adminpage-86" canEditText>Block an opening</Editable><form onSubmit={e => { e.preventDefault(); const form = e.currentTarget; const body = Object.fromEntries(new FormData(form)); action(async () => { await api('/admin/blocks', { method: 'POST', body }); form.reset(); setNotice('Time blocked.'); }); }}><Editable as="label" contentKey="adminpage-87">Date<input name="date" type="date" min={today()} required/></Editable><Editable as="label" contentKey="adminpage-88">Time<select name="time">{hours.map(t => <option key={t} value={t}>{formatTime(t)}</option>)}</select></Editable><Editable as="label" contentKey="adminpage-89">Reason<input name="reason" maxLength="200" required placeholder="Travel time, weather, time off…"/></Editable><Editable as="button" contentKey="adminpage-90" canEditText className="button button-ghost" disabled={busy}>Block time</Editable></form><Editable as="h3" contentKey="adminpage-91" canEditText>Blocked times</Editable>{data.blocks.length ? data.blocks.map(block => <Editable as="div" contentKey="adminpage-92" className="blocked-time" key={block._id}><Editable as="p" contentKey="adminpage-93">{formatDate(block.date)} · {formatTime(block.time)}<Editable as="small" contentKey="adminpage-94">{block.reason}</Editable></Editable><Editable as="button" contentKey="adminpage-95" canEditText className="quiet-button" disabled={busy} onClick={() => action(async () => { await api(`/admin/blocks/${encodeURIComponent(block._id)}`, { method: 'DELETE', body: {} }); setNotice('Time reopened.'); })}>Reopen</Editable></Editable>) : <Editable as="p" contentKey="adminpage-96" canEditText>No blocked openings.</Editable>}</Editable>
        </Editable></Editable>
      </>}
      {tab === 'messages' && <StaffInbox key={`inbox-${resetVersion}`} inbox={data.inbox} refreshInbox={load}/>}
      {tab === 'lessons' && <LessonEditor key={`lessons-${resetVersion}`}/>}
      {tab === 'people' && user.role === 'owner' && <><OwnerPanel key={`people-${resetVersion}`} user={user}/><Editable as="section" contentKey="adminpage-97" className="panel"><Editable as="h2" contentKey="adminpage-98" canEditText>Community moderation.</Editable><Editable as="p" contentKey="adminpage-99" canEditText>Review public and group conversations. Hide messages in context, or mute/block accounts in People & access.</Editable><Editable as={Link} contentKey="adminpage-100" canEditLink canEditText className="button button-ghost" to="/community?tab=groups">Review groups</Editable><Editable as={Link} contentKey="adminpage-101" canEditLink canEditText className="inline-link" to="/community">Open Bravo Room</Editable><Editable as="p" contentKey="adminpage-102" className="helper">{config?.paymentsReady ? 'Verified Stripe checkout and refund controls are available from booking records.' : 'Checkout and refunds remain safely paused until verified Stripe setup is enabled.'}</Editable></Editable></>}
      {tab === 'people' && user.role === 'staff' && <ClientDirectory/>}
      {tab === 'services' && user.role === 'owner' && <Editable as="section" contentKey="adminpage-103"><Editable as="div" contentKey="adminpage-104" className="section-label"><Editable as="div" contentKey="adminpage-105"><Editable as="p" contentKey="adminpage-106" canEditText className="kicker gold">ADMIN ACCESS</Editable><Editable as="h2" contentKey="adminpage-107" canEditText>Services & pricing.</Editable></Editable></Editable><Editable as="p" contentKey="adminpage-108" canEditText>Changes apply to new server-generated quotes. Existing bookings keep the price recorded when they were created.</Editable><Editable as="div" contentKey="adminpage-109" className="owner-people">{data.services.map(service => <form className="panel owner-person" key={`${service.id}-${resetVersion}`} onSubmit={event => { event.preventDefault(); const fields = Object.fromEntries(new FormData(event.currentTarget)); action(async () => { await api(`/admin/services/${service.id}`, { method: 'PATCH', body: { cents: Math.round(Number(fields.price) * 100), enabled: fields.enabled === 'on' } }); await refreshConfig(); setNotice(`${service.name} updated.`); }); }}><Editable as="div" contentKey="adminpage-110" className="record-top"><Editable as="span" contentKey="adminpage-111" className="badge">{service.interval}</Editable><Editable as="span" contentKey="adminpage-112" className="badge">{service.enabled ? 'Active' : 'Paused'}</Editable></Editable><Editable as="h3" contentKey="adminpage-113">{service.name}</Editable><Editable as="label" contentKey="adminpage-114">Price in dollars<input name="price" type="number" min="0" max="10000" step="0.01" defaultValue={(service.cents / 100).toFixed(2)} readOnly={service.id === 'training'}/></Editable><Editable as="label" contentKey="adminpage-115" className="check-label"><input name="enabled" type="checkbox" defaultChecked={service.enabled}/>Offer this service for new bookings</Editable>{service.id === 'training' && <Editable as="p" contentKey="adminpage-116" canEditText className="helper">Training is fixed at $200/month for the first dog and $100/month for each additional dog.</Editable>}<Editable as="button" contentKey="adminpage-117" canEditText className="button button-small" disabled={busy}>Save service</Editable></form>)}</Editable></Editable>}
      {tab === 'reviews' && user.role === 'owner' && <Editable as="section" contentKey="adminpage-118"><Editable as="div" contentKey="adminpage-119" className="section-label"><Editable as="div" contentKey="adminpage-120"><Editable as="p" contentKey="adminpage-121" canEditText className="kicker gold">MODERATION</Editable><Editable as="h2" contentKey="adminpage-122" canEditText>Customer reviews.</Editable></Editable></Editable><Editable as="p" contentKey="adminpage-123" canEditText>Hide inappropriate content without rewriting a customer’s words. Restoring a review publishes the original text unchanged.</Editable>{!data.reviews.length ? <Editable as="div" contentKey="adminpage-124" className="panel"><Editable as="p" contentKey="adminpage-125" canEditText>No customer reviews yet.</Editable></Editable> : <Editable as="div" contentKey="adminpage-126" className="admin-bookings">{data.reviews.map(review => <Editable as="article" contentKey="adminpage-127" className="panel" key={review._id}><Editable as="div" contentKey="adminpage-128" className="record-top"><Editable as="span" contentKey="adminpage-129" className="badge">{review.rating} / 5 stars</Editable>{review.hidden && <Editable as="span" contentKey="adminpage-130" canEditText className="badge">Hidden</Editable>}</Editable><Editable as="h3" contentKey="adminpage-131">{review.authorName}</Editable><Editable as="p" contentKey="adminpage-132">{review.body}</Editable><Editable as="button" contentKey="adminpage-133" className="quiet-button" disabled={busy} onClick={() => action(async () => { await api(`/admin/reviews/${review._id}`, { method: 'PATCH', body: { hidden: !review.hidden } }); setNotice(review.hidden ? 'Review restored.' : 'Review hidden.'); })}>{review.hidden ? 'Restore original review' : 'Hide review'}</Editable></Editable>)}</Editable>}</Editable>}
    </>}
  </Page>;
}
