import { trainerOptions, trainerChoice, bookingTrainerIds } from '../../shared/trainers';
import WeekendSessions from './WeekendSessions';
import TrainerClients from './TrainerClients';
import LessonEditor from './LessonEditor';
import OwnerPanel from './OwnerPanel';
import StaffInbox from './StaffInbox';
import StaffBooking from './StaffBooking';
import StaffScheduleEditor from './StaffScheduleEditor';
import ClientDirectory from './ClientDirectory';
import './trainer-schedules.css';
import { downloadCalendar } from './calendar';
import { useCallback, useEffect, useState } from 'react';
import { useLocation, Link } from 'react-router-dom';
import { useBravo } from './context';
import { api } from './api';
import { Page, Notice, AppointmentNotice, formatDate, formatTime } from './ui';
import { today } from './BookingPage';
import { ALL_SERVICES, money } from '../../shared/catalog';
import { deskLabel } from '../../shared/access';

const hours = Array.from({ length: 13 }, (_, i) => `${i + 9}:00`.padStart(5, '0'));
const serviceName = id => ALL_SERVICES.find(service => service.id === id)?.name || 'Legacy Bravo program';
export default function AdminPage() {
  const { notifications, user, config, refreshConfig, authReady, setBookingDraft } = useBravo();
  const [data, setData] = useState(null), [schedule, setSchedule] = useState(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [resetVersion, setResetVersion] = useState(0);
  const [tab, setTab] = useState(() => new URLSearchParams(window.location.search).get('tab') || 'schedule'), [query, setQuery] = useState(''), [statusFilter, setStatusFilter] = useState('active'), [visitDate, setVisitDate] = useState(''), [trainer, setTrainer] = useState('all');
  const location = useLocation();
  useEffect(() => { const wanted = new URLSearchParams(location.search).get('tab'); if (wanted && ['schedule', 'people', 'messages', 'lessons', 'services', 'reviews'].includes(wanted)) setTab(wanted); }, [location.search]);
  const load = useCallback(async () => { const result = await api('/admin'); const [reviews, services] = result.role === 'owner' ? await Promise.all([api('/admin/reviews').then(data => data.reviews), api('/admin/services').then(data => data.services)]) : [[], []]; setData({ ...result, reviews, services }); setSchedule(result.settings); }, []);
  useEffect(() => { if (['staff', 'owner'].includes(user?.role)) load().catch(e => setError(e.message)); }, [user, load]);
  useEffect(() => { if (tab !== 'messages') return; const timer = setInterval(() => { if (!document.hidden) load().catch(e => setError(e.message)); }, 15000); load().catch(e => setError(e.message)); return () => clearInterval(timer); }, [tab, location.search, load]);
  async function action(work) { setBusy(true); setError(''); setNotice(''); try { await work(); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function resetDesk() {
    if (!window.confirm('Clear unsaved desk selections, filters and forms, then reload fresh server data? Saved bookings, client accounts, messages and payments will not be deleted. Use the labelled chat controls to clear history.')) return;
    setBusy(true); setError(''); setNotice('');
    setQuery(''); setStatusFilter('active'); setVisitDate(''); setTrainer('all'); setBookingDraft(null);
    try { await Promise.all([load(), refreshConfig()]); setResetVersion(value => value + 1); setNotice('Desk selections, filters and unsaved forms reset. Saved records were reloaded without using the browser cache.'); }
    catch (err) { setError(err.message); } finally { setBusy(false); }
  }
  function toggle(field, value) { setSchedule(s => ({ ...s, [field]: s[field].includes(value) ? s[field].filter(v => v !== value) : [...s[field], value].sort() })); }
  const mine = b => trainer === 'all' || (trainer === 'unassigned' ? !bookingTrainerIds(b).length : bookingTrainerIds(b).includes(trainer));
  const visible = (data?.bookings || []).filter(b => mine(b) &&
    (statusFilter === 'all' || (statusFilter === 'active' ? b.status !== 'cancelled' : b.status === statusFilter)) &&
    (!visitDate || b.visits.some(v => v.date === visitDate)) &&
    [b.dogName, b.userId?.name, b.userId?.email, b.phone, b._id].some(v => String(v || '').toLowerCase().includes(query.toLowerCase())));
  const agenda = (data?.bookings || []).filter(b => mine(b) && !['cancelled', 'waitlisted'].includes(b.status)).flatMap(b => b.visits.filter(v => v.date === today()).map(v => ({ ...v, booking: b }))).sort((a,b) => a.time.localeCompare(b.time));
  const allowed = ['staff', 'owner'].includes(user?.role);
  const tabs = [['schedule', 'Schedule'], ['lessons', 'Lesson studio'], ['messages', 'Messages'], ...(user?.role === 'owner' ? [['people', 'People & access'], ['services', 'Services & pricing'], ['reviews', 'Reviews']] : user?.role === 'staff' ? [['people', 'People & access']] : [])];
  return <Page className="staff-page" title={`Your ${deskLabel(user).toLowerCase()}.`} eyebrow={user?.isPrimaryOwner ? 'BRAVO OWNERSHIP' : 'BRAVO OPERATIONS'} intro="Choose a task. Keep your day, your clients, and your lessons in one place.">
    <Notice error>{error}</Notice><Notice>{notice}</Notice>{allowed && <div className="reset-actions desk-reset"><button className="button button-small button-ghost" type="button" disabled={busy} onClick={resetDesk}>Refresh & reset desk</button><small>Clear unsaved forms and selections; keep saved records.</small></div>}
    {!authReady ? <p role="status">Checking access…</p> : !allowed ? <div className="panel"><h2>Team access required.</h2><p>The owner assigns staff privileges to registered accounts.</p><Link className="button" to="/account">Open your account</Link></div> : !data ? <p role="status">Loading your desk…</p> : <>
      <nav className="community-tabs desk-tabs" aria-label="Desk sections">{tabs.map(([id, label]) => <button key={id} aria-pressed={tab === id} onClick={() => { setTab(id); setError(''); setNotice(''); }}>{label}{id === 'messages' && (notifications || []).some(item=>item.unread&&item.id.startsWith('message:')) && <span className="notification-count">{(notifications || []).filter(item => item.unread && item.id.startsWith('message:')).length}</span>}</button>)}</nav>
      {tab === 'schedule' && <>
        <AppointmentNotice/>
        <section className="panel"><div className="section-label"><h2>Today’s visits.</h2><button className="quiet-button" disabled={busy} onClick={resetDesk}>Refresh & reset</button></div>
          <div className="form-grid"><p>{formatDate(today())} · Aberdeen time</p><label>View schedule<select value={trainer} onChange={e => setTrainer(e.target.value)}><option value="all">Whole team</option><option value={user.id}>My visits</option><option value="unassigned">Unassigned visits</option>{data.team.filter(person => person._id !== user.id).map(person => <option key={person._id} value={person._id}>{person.name}</option>)}</select></label></div>
          {agenda.length ? agenda.map(v => <div className="appointment-line" key={`${v.booking._id}-${v.time}`}><strong>{formatTime(v.time)} · {v.booking.dogName}</strong><span>{v.booking.userId?.name} · {v.booking.status}</span><a className="inline-link" href={`tel:${v.booking.phone.replace(/[^+0-9]/g, '')}`}>Call client</a></div>) : <p>No visits today for this view.</p>}
          <p className="helper">Requests need confirmation. Openings follow each assigned trainer’s working hours and saved visits.</p>
        </section>
        <TrainerClients key={`clients-${resetVersion}`} staffId={user.id}/><WeekendSessions/><StaffScheduleEditor key={`personal-schedule-${resetVersion}`} team={data.team}/><StaffBooking key={`booking-${resetVersion}`} team={data.team} onSaved={load}/>
        <section id="customer-requests"><h2>Requests & upcoming visits.</h2>
          <div className="panel"><div className="form-grid"><label>Find a client or dog<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Name, email, phone, or booking ID"/></label><label>Status<select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}><option value="active">Active requests, waitlist & visits</option><option value="waitlisted">Trainer waiting list</option><option value="requested">Awaiting confirmation</option><option value="confirmed">Confirmed</option><option value="cancelled">Cancelled</option><option value="all">All statuses</option></select></label><label>Visit date<input type="date" value={visitDate} onChange={e => setVisitDate(e.target.value)}/></label></div><button type="button" className="quiet-button" onClick={() => { setQuery(''); setStatusFilter('active'); setVisitDate(''); setTrainer('all'); }}>Reset filters</button><p className="helper">Showing {visible.length} of the latest {data.bookings.length} requests.</p></div>
          {!visible.length ? <div className="panel"><p>No requests match this view.</p></div> : <div className="admin-bookings">{visible.map(booking => <article className="panel" key={booking._id}>
            <div className="record-top"><span className="badge">{booking.status}</span><span className="badge">{booking.paymentStatus}</span></div><h3>{booking.dogName}</h3><p>{booking.serviceIds.map(serviceName).join(' + ')}{booking.serviceIds.some(id => ['training', 'walking'].includes(id)) ? ` · ${booking.dogCount || 1} ${(booking.dogCount || 1) === 1 ? 'dog' : 'dogs'}` : ''} · {money(booking.quote?.dueNowCents || 0)} due</p><p>{booking.userId?.name || 'Former client'} · {booking.userId?.email}</p><p><a className="inline-link" href={`tel:${booking.phone.replace(/[^+0-9]/g, '')}`}>{booking.phone}</a><br/>{booking.address}</p>{booking.notes && <p className="staff-note">{booking.notes}</p>}
            {booking.userId?._id && <Link className="button button-small" to={`/schedule?client=${booking.userId._id}`}>Client schedule & PDF</Link>}
            {booking.status === 'waitlisted' && <Notice>Waiting-list request. These are preferred dates only and are not reserved. Choose a trainer below to activate it when capacity and the requested times are available.</Notice>}
            {booking.visits.map(v => <div className="appointment-line" key={`${v.date}-${v.time}`}><strong>{formatDate(v.date)}</strong><span>{formatTime(v.time)} · {v.service}</span></div>)}
            {booking.trainerAcceptanceRequired&&<p className="helper">Awaiting trainer acceptance. Open Training clients above or the trainer’s profile to accept.</p>}<label>{booking.status === 'waitlisted' ? 'Preferred trainer / activate request' : 'Assigned trainer'}<select disabled={busy || booking.status === 'cancelled'} value={booking.staffId ? trainerChoice(booking) : ''} onChange={e => action(() => api(`/admin/bookings/${booking._id}/assignment`, { method: 'PATCH', body: { staffId: e.target.value || null } }))}><option value="">{booking.requestedStaffId ? `Waiting for ${trainerOptions(data.team).find(person => person._id === trainerChoice(booking))?.name || 'chosen trainer'}` : 'Unassigned'}</option>{booking.staffId && !data.team.some(person => person._id === booking.staffId) && <option value={booking.staffId}>Former staff — reassign this visit</option>}{trainerOptions(data.team).map(person => <option key={person._id} value={person._id} disabled={person.disabled}>{person.name}</option>)}</select></label>
            {booking.status !== 'cancelled' && <div className="record-actions">{booking.status === 'confirmed' && booking.visits.length > 0 && <button className="quiet-button" onClick={() => downloadCalendar(booking)}>Add to calendar</button>}
              {booking.visits.length > 0 && !booking.stripeSessionId && <Link className="quiet-button" to={`/portal?edit=${booking._id}`}>Change dates or times</Link>}
              {booking.status === 'requested' && <button className="button button-small" disabled={busy} onClick={() => action(() => api(`/admin/bookings/${booking._id}`, { method: 'PATCH', body: { status: 'confirmed' } }))}>Confirm visit</button>}
              <button className="quiet-button" disabled={busy} onClick={() => { if(window.confirm('Cancel this visit? This does not refund a payment.')) action(() => api(`/admin/bookings/${booking._id}`, { method: 'PATCH', body: { status: 'cancelled' } })); }}>Cancel visit</button>
            </div>}
            {user.role === 'owner' && ['paid', 'review'].includes(booking.paymentStatus) && (config?.paymentsReady ? <button className="quiet-button danger-link" disabled={busy} onClick={() => { if (window.confirm(`Issue the verified ${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((booking.quote?.dueNowCents || 0)/100)} refund through Stripe? This cannot be undone here.`)) action(async () => { const result = await api(`/admin/bookings/${booking._id}/refund`, { method: 'POST', body: {} }); setNotice(result.message); }); }}>{booking.refundId ? 'Check Stripe refund' : 'Issue Stripe refund'}</button> : <p className="helper">Refund control will activate only after verified Stripe setup is enabled.</p>)}
          </article>)}</div>}
        </section>
        <details className="panel" key={`availability-${resetVersion}`}><summary>Shared team calendar & closures</summary><p>These settings apply to the shared team calendar. Existing visits stay booked.</p><div className="admin-layout">
          <section><h3>Weekly availability</h3><form onSubmit={e => { e.preventDefault(); action(async () => { await api('/admin/schedule', { method: 'PUT', body: { enabled: schedule.enabled, weekdays: schedule.weekdays, hours: schedule.hours } }); await refreshConfig(); setNotice('Availability updated.'); }); }}><label className="check-label"><input type="checkbox" checked={schedule.enabled} onChange={e => setSchedule(s => ({ ...s, enabled: e.target.checked }))}/>Accept online booking requests</label><fieldset><legend>Working days</legend><div className="check-grid">{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((label,i) => <label className="check-label" key={label}><input type="checkbox" disabled={i >= 5 && user.role !== 'owner'} checked={schedule.weekdays.includes(i+1)} onChange={() => toggle('weekdays',i+1)}/>{label}</label>)}</div></fieldset><fieldset><legend>Starting times</legend><div className="check-grid">{hours.map(time => <label className="check-label" key={time}><input type="checkbox" checked={schedule.hours.includes(time)} onChange={() => toggle('hours',time)}/>{formatTime(time)}</label>)}</div></fieldset><div className="reset-actions"><button className="button" disabled={busy}>Save availability</button><button type="button" className="quiet-button" disabled={busy} onClick={() => { setSchedule(current => ({ ...current, weekdays: [], hours: [] })); setNotice('Availability selections cleared locally. Choose the new days and times before saving. Existing appointments were not changed.'); }}>Reset availability selections</button></div></form></section>
          <section><h3>Block an opening</h3><form onSubmit={e => { e.preventDefault(); const form = e.currentTarget; const body = Object.fromEntries(new FormData(form)); action(async () => { await api('/admin/blocks', { method: 'POST', body }); form.reset(); setNotice('Time blocked.'); }); }}><label>Date<input name="date" type="date" min={today()} required/></label><label>Time<select name="time">{hours.map(t => <option key={t} value={t}>{formatTime(t)}</option>)}</select></label><label>Reason<input name="reason" maxLength="200" required placeholder="Travel time, weather, time off…"/></label><button className="button button-ghost" disabled={busy}>Block time</button></form><h3>Blocked times</h3>{data.blocks.length ? data.blocks.map(block => <div className="blocked-time" key={block._id}><p>{formatDate(block.date)} · {formatTime(block.time)}<small>{block.reason}</small></p><button className="quiet-button" disabled={busy} onClick={() => action(() => api(`/admin/blocks/${encodeURIComponent(block._id)}`, { method: 'DELETE', body: {} }))}>Reopen</button></div>) : <p>No blocked openings.</p>}</section>
        </div></details>
      </>}
      {tab === 'messages' && <StaffInbox key={`inbox-${resetVersion}`} inbox={data.inbox} refreshInbox={load}/>}
      {tab === 'lessons' && <LessonEditor key={`lessons-${resetVersion}`}/>}
      {tab === 'people' && user.role === 'owner' && <><OwnerPanel key={`people-${resetVersion}`} user={user}/><section className="panel"><h2>Community moderation.</h2><p>Review public and group conversations. Hide messages in context, or mute/block accounts in People & access.</p><Link className="button button-ghost" to="/community?tab=groups">Review groups</Link><Link className="inline-link" to="/community">Open Bravo Room</Link><p className="helper">{config?.paymentsReady ? 'Verified Stripe checkout and refund controls are available from booking records.' : 'Checkout and refunds remain safely paused until verified Stripe setup is enabled.'}</p></section></>}
      {tab === 'people' && user.role === 'staff' && <ClientDirectory/>}
      {tab === 'services' && user.role === 'owner' && <section><div className="section-label"><div><p className="kicker gold">ADMIN ACCESS</p><h2>Services & pricing.</h2></div></div><p>Changes apply to new server-generated quotes. Existing bookings keep the price recorded when they were created.</p><div className="owner-people">{data.services.map(service => <form className="panel owner-person" key={`${service.id}-${resetVersion}`} onSubmit={event => { event.preventDefault(); const fields = Object.fromEntries(new FormData(event.currentTarget)); action(async () => { await api(`/admin/services/${service.id}`, { method: 'PATCH', body: { cents: Math.round(Number(fields.price) * 100), enabled: fields.enabled === 'on' } }); await refreshConfig(); setNotice(`${service.name} updated.`); }); }}><div className="record-top"><span className="badge">{service.interval}</span><span className="badge">{service.enabled ? 'Active' : 'Paused'}</span></div><h3>{service.name}</h3><label>Price in dollars<input name="price" type="number" min="0" max="10000" step="0.01" defaultValue={(service.cents / 100).toFixed(2)} readOnly={service.id === 'training'}/></label><label className="check-label"><input name="enabled" type="checkbox" defaultChecked={service.enabled}/>Offer this service for new bookings</label>{service.id === 'training' && <p className="helper">Training is fixed at $200/month for the first dog and $100/month for each additional dog.</p>}<button className="button button-small" disabled={busy}>Save service</button></form>)}</div></section>}
      {tab === 'reviews' && user.role === 'owner' && <section><div className="section-label"><div><p className="kicker gold">MODERATION</p><h2>Customer reviews.</h2></div></div><p>Hide inappropriate content without rewriting a customer’s words. Restoring a review publishes the original text unchanged.</p>{!data.reviews.length ? <div className="panel"><p>No customer reviews yet.</p></div> : <div className="admin-bookings">{data.reviews.map(review => <article className="panel" key={review._id}><div className="record-top"><span className="badge">{review.rating} / 5 stars</span>{review.hidden && <span className="badge">Hidden</span>}</div><h3>{review.authorName}</h3><p>{review.body}</p><button className="quiet-button" disabled={busy} onClick={() => action(() => api(`/admin/reviews/${review._id}`, { method: 'PATCH', body: { hidden: !review.hidden } }))}>{review.hidden ? 'Restore original review' : 'Hide review'}</button></article>)}</div>}</section>}
    </>}
  </Page>;
}
