import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useBravo } from './context';
import { api } from './api';
import { Page, Notice, formatDate, formatTime } from './ui';
import { today } from './BookingPage';
const hours = Array.from({ length: 13 }, (_, i) => `${i + 9}:00`.padStart(5, '0'));
export default function AdminPage() {
  const { user, refreshConfig, authReady } = useBravo();
  const [data, setData] = useState(null), [schedule, setSchedule] = useState(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const result = await api('/admin'); setData(result); setSchedule(result.settings); }, []);
  useEffect(() => { if (user?.role === 'staff') load().catch(e => setError(e.message)); }, [user, load]);
  async function action(work) { setBusy(true); setError(''); setNotice(''); try { await work(); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  function toggle(field, value) { setSchedule(s => ({ ...s, [field]: s[field].includes(value) ? s[field].filter(v => v !== value) : [...s[field], value].sort() })); }
  return <Page title="The staff desk." eyebrow="BRAVO OPERATIONS" intro="Set real availability, review booking requests, and keep the team’s calendar clear."><Notice error>{error}</Notice><Notice>{notice}</Notice>{!authReady ? <p role="status">Checking staff access…</p> : user?.role !== 'staff' ? <div className="panel"><h2>Bravo staff access required.</h2><p>Staff privileges are assigned by the account owner. Public registration never grants staff access.</p><Link className="button" to="/account">Open your account</Link></div> : !data ? <p role="status">Loading the staff desk…</p> : <>
    <div className="admin-layout"><section className="panel"><h2>Weekly availability.</h2><p>All times use Aberdeen’s local time. Existing visits stay booked if you change these settings.</p><form onSubmit={e => { e.preventDefault(); action(async () => { await api('/admin/schedule', { method: 'PUT', body: { enabled: schedule.enabled, weekdays: schedule.weekdays, hours: schedule.hours } }); await refreshConfig(); setNotice('Availability updated.'); }); }}><label className="check-label"><input type="checkbox" checked={schedule.enabled} onChange={e => setSchedule(s => ({ ...s, enabled: e.target.checked }))}/>Accept online booking requests</label><fieldset><legend>Working days</legend><div className="check-grid">{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((label,i) => <label className="check-label" key={label}><input type="checkbox" checked={schedule.weekdays.includes(i+1)} onChange={() => toggle('weekdays',i+1)}/>{label}</label>)}</div></fieldset><fieldset><legend>Available starting times</legend><div className="check-grid">{hours.map(time => <label className="check-label" key={time}><input type="checkbox" checked={schedule.hours.includes(time)} onChange={() => toggle('hours',time)}/>{formatTime(time)}</label>)}</div></fieldset><p className="helper">The schedule starts closed until you enable it. It supports one visit per hourly opening across training and sitting. Adjust openings to allow travel time.</p><button className="button" disabled={busy}>Save availability</button></form></section>
    <section className="panel"><h2>Block an opening.</h2><form onSubmit={e => { e.preventDefault(); const form = e.currentTarget; action(async () => { await api('/admin/blocks', { method: 'POST', body: Object.fromEntries(new FormData(form)) }); setNotice('Time blocked.'); }); }}><label>Date<input name="date" type="date" min={today()} required/></label><label>Time<select name="time">{hours.map(t => <option key={t} value={t}>{formatTime(t)}</option>)}</select></label><label>Reason<input name="reason" maxLength="200" required placeholder="Travel time, weather, time off…"/></label><button className="button button-ghost" disabled={busy}>Block time</button></form><h3>Blocked times</h3>{data.blocks.length ? data.blocks.map(block => <div className="blocked-time" key={block._id}><p>{formatDate(block.date)} · {formatTime(block.time)}<small>{block.reason}</small></p><button className="quiet-button" disabled={busy} onClick={() => action(() => api(`/admin/blocks/${encodeURIComponent(block._id)}`, { method: 'DELETE', body: {} }))}>Reopen</button></div>) : <p>No blocked openings.</p>}</section></div>
    <section><h2>Customer requests.</h2>{!data.bookings.length ? <div className="panel"><p>No booking requests yet.</p></div> : <div className="admin-bookings">{data.bookings.map(booking => <article className="panel" key={booking._id}><div className="record-top"><span className="badge">{booking.status}</span><span className="badge">{booking.paymentStatus}</span></div><h3>{booking.dogName}</h3><p>{booking.userId?.name} · {booking.userId?.email}</p><p>{booking.phone}<br/>{booking.address}</p>{booking.notes && <p className="staff-note">{booking.notes}</p>}{booking.visits.map(v => <div className="appointment-line" key={`${v.date}-${v.time}`}><strong>{formatDate(v.date)}</strong><span>{formatTime(v.time)} · {v.service}</span></div>)}{booking.status !== 'cancelled' && <div className="record-actions">{booking.status === 'requested' && <button className="button button-small" disabled={busy} onClick={() => action(() => api(`/admin/bookings/${booking._id}`, { method: 'PATCH', body: { status: 'confirmed' } }))}>Confirm visit</button>}<button className="quiet-button" disabled={busy} onClick={() => { if(window.confirm('Cancel this request? No refund or subscription cancellation is issued.')) action(() => api(`/admin/bookings/${booking._id}`, { method: 'PATCH', body: { status: 'cancelled' } })); }}>Cancel request</button></div>}</article>)}</div>}</section>
    <section className="panel prose"><h2>Lessons & announcements.</h2><p>Post official announcements and urgent alerts in the <Link className="inline-link" to="/community">Bravo Room</Link>. Lesson publishing requires an actual private video file, a caption file, and a transcript. The setup guide explains how to publish these safely.</p></section>
    </>}</Page>;
}
