import { Link } from 'react-router-dom';
import { AppointmentNotice, Page } from './ui';

export default function BehaviorAssessmentPage() {
  return <Page title="Dog behavior assessments in Aberdeen." eyebrow="A FOCUSED FIRST STEP" intro="When aggression or difficult handling is the main concern, start with Bravo’s aggressive-dog intake. Two trainers review the situation with you before discussing an ongoing plan.">
    <section className="panel prose"><h2>Start with understanding.</h2><p>Tell the team what you are seeing, when it happens and what you want help with. The initial assessment gives Bravo a chance to learn your dog’s history and review behavior and handling with you.</p><p>This is a separate intake service from the monthly professional training program. The next steps depend on the assessment and a conversation with the team.</p><Link className="button" to="/portal?program=aggression">Request a behavior assessment</Link><p><a href="tel:+16058242767">Discuss your concerns: (605) 824-2767</a></p></section>
    <section className="panel prose"><h2>What to share with Bravo.</h2><ul><li>The situations where you notice the behavior, including reactions around people, dogs or handling.</li><li>Your dog’s background and any previous training.</li><li>Practical concerns about meeting your dog and working at your home.</li><li>Your goals and questions for the trainers.</li></ul><p>Call before the visit to discuss handling or access concerns. Keep personal details in the private booking notes or your conversation with the team.</p></section>
    <section className="panel prose service-questions"><h2>Before you book.</h2><details><summary>Where does Bravo work?</summary><p>Bravo K9 Solutions provides mobile dog training in Aberdeen, South Dakota. Contact the team to confirm your location and arrangements for the assessment.</p></details><details><summary>Is ongoing training included in the intake?</summary><p>The intake is an initial assessment with two trainers. Bravo will discuss any ongoing training separately after reviewing your dog’s needs.</p></details><details><summary>How do I see the price and available times?</summary><p>Choose “Request a behavior assessment” to see the current intake price and available appointments. Saving a request does not charge your card, and Bravo must confirm the visit.</p></details><details><summary>What if I need help with obedience instead?</summary><p>Explore <Link to="/dog-training">private dog training</Link> for puppy foundations, obedience and everyday behavior. If you are unsure where to start, call Bravo.</p></details></section>
    <AppointmentNotice/>
  </Page>;
}
