import { Editable } from './SiteContent';
import { Link } from 'react-router-dom';
import { AppointmentNotice, Page } from './ui';

export default function BehaviorAssessmentPage() {
  return <Page title="Dog behavior assessments in Aberdeen." eyebrow="A FOCUSED FIRST STEP" intro="When aggression or difficult handling is the main concern, start with Bravo’s aggressive-dog intake. Two trainers review the situation with you before discussing an ongoing plan.">
    <Editable as="section" contentKey="behaviorassessmentpage-1" className="panel prose"><Editable as="h2" contentKey="behaviorassessmentpage-2" canEditText>Start with understanding.</Editable><Editable as="p" contentKey="behaviorassessmentpage-3" canEditText>Tell the team what you are seeing, when it happens and what you want help with. The initial assessment gives Bravo a chance to learn your dog’s history and review behavior and handling with you.</Editable><Editable as="p" contentKey="behaviorassessmentpage-4" canEditText>This is a separate intake service from the monthly professional training program. The next steps depend on the assessment and a conversation with the team.</Editable><Editable as={Link} contentKey="behaviorassessmentpage-5" canEditLink canEditText className="button" to="/portal?program=aggression">Request a behavior assessment</Editable><Editable as="p" contentKey="behaviorassessmentpage-6"><Editable as="a" contentKey="behaviorassessmentpage-7" canEditLink canEditText href="tel:+16058242767">Discuss your concerns: (605) 824-2767</Editable></Editable></Editable>
    <Editable as="section" contentKey="behaviorassessmentpage-8" className="panel prose"><Editable as="h2" contentKey="behaviorassessmentpage-9" canEditText>What to share with Bravo.</Editable><Editable as="ul" contentKey="behaviorassessmentpage-10"><Editable as="li" contentKey="behaviorassessmentpage-11" canEditText>The situations where you notice the behavior, including reactions around people, dogs or handling.</Editable><Editable as="li" contentKey="behaviorassessmentpage-12" canEditText>Your dog’s background and any previous training.</Editable><Editable as="li" contentKey="behaviorassessmentpage-13" canEditText>Practical concerns about meeting your dog and working at your home.</Editable><Editable as="li" contentKey="behaviorassessmentpage-14" canEditText>Your goals and questions for the trainers.</Editable></Editable><Editable as="p" contentKey="behaviorassessmentpage-15" canEditText>Call before the visit to discuss handling or access concerns. Keep personal details in the private booking notes or your conversation with the team.</Editable></Editable>
    <Editable as="section" contentKey="behaviorassessmentpage-16" className="panel prose service-questions"><Editable as="h2" contentKey="behaviorassessmentpage-17" canEditText>Before you book.</Editable><Editable as="details" contentKey="behaviorassessmentpage-18"><Editable as="summary" contentKey="behaviorassessmentpage-19" canEditText>Where does Bravo work?</Editable><Editable as="p" contentKey="behaviorassessmentpage-20" canEditText>Bravo K9 Solutions provides mobile dog training in Aberdeen, South Dakota. Contact the team to confirm your location and arrangements for the assessment.</Editable></Editable><Editable as="details" contentKey="behaviorassessmentpage-21"><Editable as="summary" contentKey="behaviorassessmentpage-22" canEditText>Is ongoing training included in the intake?</Editable><Editable as="p" contentKey="behaviorassessmentpage-23" canEditText>The intake is an initial assessment with two trainers. Bravo will discuss any ongoing training separately after reviewing your dog’s needs.</Editable></Editable><Editable as="details" contentKey="behaviorassessmentpage-24"><Editable as="summary" contentKey="behaviorassessmentpage-25" canEditText>How do I see the price and available times?</Editable><Editable as="p" contentKey="behaviorassessmentpage-26" canEditText>Choose “Request a behavior assessment” to see the current intake price and available appointments. Saving a request does not charge your card, and Bravo must confirm the visit.</Editable></Editable><Editable as="details" contentKey="behaviorassessmentpage-27"><Editable as="summary" contentKey="behaviorassessmentpage-28" canEditText>What if I need help with obedience instead?</Editable><Editable as="p" contentKey="behaviorassessmentpage-29">Explore <Editable as={Link} contentKey="behaviorassessmentpage-30" canEditLink canEditText to="/dog-training">private dog training</Editable> for puppy foundations, obedience and everyday behavior. If you are unsure where to start, call Bravo.</Editable></Editable></Editable>
    <AppointmentNotice/>
  </Page>;
}
