import { Editable } from './SiteContent';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from './api';
import { Page, Notice } from './ui';

export default function ContactPage() {
  const [team, setTeam] = useState([]), [error, setError] = useState('');
  useEffect(() => { api('/team').then(data => setTeam(data.team)).catch(e => setError(e.message)); }, []);
  return <Page title="Talk to Bravo." eyebrow="ABERDEEN, SOUTH DAKOTA" intro="Training questions, an upcoming visit, or your account—reach the right person without hunting through the site.">
    <Notice error>{error}</Notice>
    <Editable as="section" contentKey="contactpage-1" className="panel prose"><Editable as="h2" contentKey="contactpage-2" canEditText>Mobile service in Aberdeen, South Dakota.</Editable><Editable as="p" contentKey="contactpage-3">Bravo K9 Solutions comes to you for <Editable as={Link} contentKey="contactpage-4" canEditLink canEditText to="/dog-training">private dog training</Editable> and offers <Editable as={Link} contentKey="contactpage-5" canEditLink canEditText to="/dog-walking">professional dog walking</Editable>. Call <Editable as="a" contentKey="contactpage-6" canEditLink canEditText href="tel:+16058242767">(605) 824-2767</Editable> to discuss your dog, confirm service at your location or get help choosing a program.</Editable><Editable as="p" contentKey="contactpage-7" canEditText>Visits are by appointment. The booking calendar shows available times; your request needs Bravo’s confirmation.</Editable></Editable>
    <Editable as="div" contentKey="contactpage-8" className="contact-grid">
      <Editable as="section" contentKey="contactpage-9" className="panel"><Editable as="p" contentKey="contactpage-10" canEditText className="kicker gold">CALL A TRAINER</Editable><Editable as="h2" contentKey="contactpage-11" canEditText>Your Bravo team.</Editable>{team.length ? <Editable as="div" contentKey="contactpage-12" className="team-contact-list">{team.map(person => <Editable as="article" contentKey="contactpage-13" key={person.id}><Editable as="div" contentKey="contactpage-14"><Editable as="strong" contentKey="contactpage-15">{person.name}</Editable><Editable as="span" contentKey="contactpage-16" className="badge">{person.role === 'owner' ? 'OWNER' : 'STAFF'}</Editable><Editable as="small" contentKey="contactpage-17">{person.title}</Editable>{person.bio && <Editable as="p" contentKey="contactpage-18">{person.bio}</Editable>}</Editable>{person.phone ? <Editable as="a" contentKey="contactpage-19" className="button button-small button-ghost" href={`tel:${person.phone.replace(/[^+\d]/g, '')}`}>Call {person.name.split(' ')[0]} · {person.phone}</Editable> : <Editable as={Link} contentKey="contactpage-20" className="inline-link" to={`/community?tab=direct&to=${person.id}`}>Message {person.name.split(' ')[0]}</Editable>}</Editable>)}</Editable> : <><Editable as="p" contentKey="contactpage-21" canEditText>Call the main Bravo line for training and scheduling help.</Editable><Editable as="a" contentKey="contactpage-22" canEditLink canEditText className="button" href="tel:+16058242767">Call (605) 824-2767</Editable></>}</Editable>
      <Editable as="section" contentKey="contactpage-23" className="panel"><Editable as="h2" contentKey="contactpage-24" canEditText>Message the team.</Editable><Editable as="p" contentKey="contactpage-25" canEditText>Signed-in clients can privately message Bravo. The thread stays with your profile so any available staff member can help.</Editable><Editable as={Link} contentKey="contactpage-26" canEditLink canEditText className="button button-ghost" to="/community?tab=direct">Open private messages</Editable><Editable as="p" contentKey="contactpage-27" canEditText className="helper">For urgent matters, call instead of waiting for a reply.</Editable></Editable>
      <Editable as="section" contentKey="contactpage-28" className="panel"><Editable as="h2" contentKey="contactpage-29" canEditText>Before your visit.</Editable><Editable as="p" contentKey="contactpage-30" canEditText>Keep your phone number and visit address current in your account. Add training goals and access instructions to the private booking notes.</Editable><Editable as="p" contentKey="contactpage-31" canEditText>A saved request still needs Bravo’s confirmation. Check your account for its current status.</Editable><Editable as={Link} contentKey="contactpage-32" canEditLink canEditText className="inline-link" to="/account">Manage my account →</Editable></Editable>
      <Editable as="section" contentKey="contactpage-33" className="panel"><Editable as="h2" contentKey="contactpage-34" canEditText>Quick answers.</Editable><Editable as="details" contentKey="contactpage-35"><Editable as="summary" contentKey="contactpage-36" canEditText>How do I change a visit?</Editable><Editable as="p" contentKey="contactpage-37" canEditText>Open My schedule from the menu and choose Add or Cancel Date. Select dates, choose times and save your changes. The Bravo team can also help you update visits.</Editable></Editable><Editable as="details" contentKey="contactpage-38"><Editable as="summary" contentKey="contactpage-39" canEditText>How do I cancel?</Editable><Editable as="p" contentKey="contactpage-40" canEditText>Open My schedule to manage your visits. Use Add or Cancel Date to remove selected visits, then save the changes. Contact Bravo for payment or refund questions.</Editable></Editable><Editable as="details" contentKey="contactpage-41"><Editable as="summary" contentKey="contactpage-42" canEditText>I forgot my password.</Editable><Editable as="p" contentKey="contactpage-43" canEditText>Call Bravo so the owner can verify your identity and help with recovery. Never post your password in the community.</Editable></Editable></Editable>
    </Editable>
  </Page>;
}
