import { Link } from 'react-router-dom';
import { Page } from './ui';
export default function ContactPage() {
  return <Page title="Talk to Bravo." eyebrow="ABERDEEN, SOUTH DAKOTA" intro="Questions about a program, an upcoming visit, or your account? Reach the Bravo team directly.">
    <div className="contact-grid"><section className="panel"><p className="kicker gold">WE COME TO YOU</p><h2>Mobile training. Local care.</h2><p>Bravo K9 Solutions serves Aberdeen and nearby communities. Call to confirm travel availability for your address.</p><a className="button" href="tel:+16058242767">Call (605) 824-2767</a><p>Available appointment times are shown in the booking calendar, in Aberdeen’s local time.</p><Link className="inline-link" to="/portal">Find an appointment</Link></section>
    <section className="panel"><h2>Before your visit.</h2><p>Keep your phone number and visit address current in your account. Add access instructions and behavior concerns to the private booking notes so the team can prepare.</p><p>A saved request still needs Bravo’s confirmation. Check your account for its current status.</p><Link className="inline-link" to="/account">Manage my account</Link></section>
    <section className="panel"><h2>Booking help.</h2><details><summary>How do I change a visit?</summary><p>Open My account and choose Change visits on an eligible request. For a request already linked to checkout, call Bravo for help.</p></details><details><summary>How do I cancel?</summary><p>Use Cancel request in your account. Cancelling a visit does not automatically refund payments or cancel a monthly subscription. Contact Bravo about billing arrangements.</p></details><details><summary>Can I book sitting for several days?</summary><p>Choose Dog sitting in the booking calendar, enter your date range, and use the automatic schedule. Review every selected day and any unavailable days before saving.</p><Link className="inline-link" to="/portal/dog-sitting">Schedule dog sitting</Link></details></section>
    <section className="panel"><h2>Account & learning help.</h2><details><summary>I forgot my password.</summary><p>Call Bravo so the team can verify your identity and help with recovery. Never post your password in the Bravo Room.</p></details><details><summary>Where are my lessons?</summary><p>Published videos, captions, and transcripts appear in Online training. Playback requires active online membership. Upcoming topics are marked Coming soon.</p><Link className="inline-link" to="/learn">Browse lessons</Link></details><details><summary>Where do I see team updates?</summary><p>Sign in and open the Bravo Room for announcements and community conversation. For time-sensitive scheduling questions, call the team.</p></details></section></div>
  </Page>;
}
