import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from './api';
import { Page } from './ui';
import { useBravo } from './context';
import { Editable } from './SiteContent';
export default function CourseLaunch() {
  const { user } = useBravo();
  const [email, setEmail] = useState(''), [consent, setConsent] = useState(false), [website, setWebsite] = useState(''), [busy, setBusy] = useState(false), [saved, setSaved] = useState(false), [error, setError] = useState('');
  async function join(event) {
    event.preventDefault(); setBusy(true); setError('');
    try { await api('/course-interest', { method: 'POST', body: { email, consent, website } }); setSaved(true); }
    catch (cause) { setError(cause.message); } finally { setBusy(false); }
  }
  return <Page title="Bravo. Anywhere." eyebrow="ONLINE COURSES · COMING SOON" intro="Learn what to do, why it matters, and how to practice it at home.">
    {user?.role === 'owner' && <p><Editable as={Link} contentKey="copy-courselaunch-1" canEditText canEditLink to="/learn">Back to library preview &amp; launch-update requests →</Editable></p>}
    <Editable as="section" contentKey="copy-courselaunch-2" className="course-launch-hero"><img src="/images/training-education.webp" width="1600" height="900" alt="A handler demonstrating clear communication with a dog"/><div><Editable as="h2" contentKey="discovery-course-title" canEditText>Learn from Bravo.<br/>Wherever you are.</Editable><Editable as="p" contentKey="discovery-course-copy" canEditText>David and Ashley are building practical dog-training lessons you can follow from home, at your own pace.</Editable><Editable as="p" contentKey="copy-courselaunch-3" canEditText>The library is not open for public enrollment yet. A launch date has not been announced.</Editable></div></Editable>
    <Editable as="section" contentKey="copy-courselaunch-4" className="service-journey"><Editable as="h2" contentKey="course-public-1" canEditText>What we’re preparing.</Editable><div className="course-topics"><Editable as="article" contentKey="copy-courselaunch-5"><Editable as="h3" contentKey="course-public-2" canEditText>Read the dog</Editable><Editable as="p" contentKey="course-public-3" canEditText>How Bravo looks at behavior, context, and the dog in front of you.</Editable></Editable><Editable as="article" contentKey="copy-courselaunch-6"><Editable as="h3" contentKey="course-public-4" canEditText>See the work</Editable><Editable as="p" contentKey="course-public-5" canEditText>Demonstrations that connect the explanation to the session.</Editable></Editable><Editable as="article" contentKey="copy-courselaunch-7"><Editable as="h3" contentKey="course-public-6" canEditText>Practice at home</Editable><Editable as="p" contentKey="course-public-7" canEditText>Lessons you can revisit, with clear written guidance beside the videos.</Editable></Editable></div><Editable as={Link} contentKey="copy-courselaunch-8" canEditText canEditLink className="inline-link" to="/#reviews">See Bravo’s public training videos →</Editable></Editable>
    <Editable as="section" contentKey="copy-courselaunch-9" className="panel course-signup" aria-labelledby="course-signup-title"><Editable as="h2" contentKey="course-public-8" canEditText id="course-signup-title">Be there when it opens.</Editable>{saved ? <Editable as="p" contentKey="copy-courselaunch-10" canEditText role="status">Your launch-update request is saved. Bravo can contact you at this address when courses open.</Editable> : <form onSubmit={join}><label><Editable as="span" contentKey="copy-courselaunch-11" canEditText>Email address</Editable><input type="email" required maxLength={254} autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} disabled={busy}/></label><label className="signup-trap" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e => setWebsite(e.target.value)}/></label><label className="check"><input type="checkbox" required checked={consent} disabled={busy} onChange={e => setConsent(e.target.checked)}/><Editable as="span" contentKey="copy-courselaunch-12" canEditText>Email me once when Bravo online courses launch.</Editable></label><Editable as="p" contentKey="copy-courselaunch-13" canEditText className="helper">No payment or account required. Bravo keeps this request for up to one year. To remove it sooner, call (605) 824-2767.</Editable>{error && <p role="alert">{error}<Editable as="span" contentKey="copy-courselaunch-14" canEditText> Your email has not been cleared; try again.</Editable></p>}<button type="submit" className="button" disabled={busy || !consent}>{busy ? 'Saving…' : 'Request a launch update'}</button></form>}</Editable>
    <p><Editable as="span" contentKey="copy-courselaunch-15" canEditText>Want hands-on help now? </Editable><Editable as={Link} contentKey="copy-courselaunch-17" canEditText canEditLink to="/dog-training">Explore private training</Editable><Editable as="span" contentKey="copy-courselaunch-16" canEditText> or </Editable><Editable as={Link} contentKey="copy-courselaunch-18" canEditText canEditLink to="/workshops">see workshops</Editable>.</p>
  </Page>;
}
export function CourseInterests() {
  const [rows, setRows] = useState([]), [next, setNext] = useState(null), [loaded, setLoaded] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function load(after = null) { setBusy(true); setError(''); try { const data = await api(`/admin/course-interest${after ? `?before=${after}` : ''}`); setRows(old => after ? [...old, ...data.interests] : data.interests); setNext(data.next); setLoaded(true); } catch (cause) { setError(cause.message); } finally { setBusy(false); } }
  async function remove(row) { if (!window.confirm(`Remove the launch-update request for ${row.email}?`)) return; setBusy(true); setError(''); try { await api(`/admin/course-interest/${row._id}`, { method: 'DELETE', body: {} }); setRows(old => old.filter(item => item._id !== row._id)); } catch (cause) { setError(cause.message); } finally { setBusy(false); } }
  return <details className="panel course-interest-admin" onToggle={e => { if (e.currentTarget.open && !loaded && !busy) load(); }}><Editable as="summary" contentKey="copy-courselaunch-19" canEditText>Course launch-update requests</Editable><Editable as="p" contentKey="copy-courselaunch-20" canEditText>These people requested one email when courses launch. This list does not send emails automatically. Honor removals and contact people only for the requested launch update.</Editable>{error && <p role="alert">{error}</p>}{busy && <Editable as="p" contentKey="copy-courselaunch-21" canEditText role="status">Updating…</Editable>}{loaded && !rows.length && <Editable as="p" contentKey="copy-courselaunch-22" canEditText>No launch-update requests yet.</Editable>}<ul>{rows.map(row => <li key={row._id}><span>{row.email}<small><Editable as="span" contentKey="copy-courselaunch-23" canEditText>Requested </Editable>{new Date(row.createdAt).toLocaleDateString()}</small></span><Editable as="button" contentKey="copy-courselaunch-24" canEditText type="button" disabled={busy} onClick={() => remove(row)}>Remove request</Editable></li>)}</ul>{next && <Editable as="button" contentKey="copy-courselaunch-25" canEditText type="button" disabled={busy} onClick={() => load(next)}>Load more requests</Editable>}<Editable as="button" contentKey="copy-courselaunch-26" canEditText type="button" disabled={busy} onClick={() => load()}>Refresh requests</Editable></details>;
}
