import TrainingFacts from './TrainingFacts';
import { Editable } from './SiteContent';
import { Link } from 'react-router-dom';
import { AppointmentNotice, Page } from './ui';

export default function DogTrainingPage() {
  return <Page title="Dog training in Aberdeen, SD." eyebrow="PRIVATE TRAINING · WE COME TO YOU" intro="Build everyday skills at home and in the places your dog needs them. Bravo K9 Solutions brings private mobile training to you in Aberdeen, South Dakota.">
    <Editable as="section" contentKey="dogtrainingpage-1" className="service-overview panel"><Editable as="div" contentKey="dogtrainingpage-2"><Editable as="h2" contentKey="dogtrainingpage-3" canEditText>A plan for your dog and your daily life.</Editable><Editable as="p" contentKey="dogtrainingpage-4" canEditText>Start with the things you want to improve: calmer walks, clearer boundaries, puppy routines or more dependable obedience. Your trainer learns about your dog, your home and your goals, then helps you practice a consistent approach.</Editable><Editable as="p" contentKey="dogtrainingpage-5" canEditText>$200/month for one dog includes private training Monday–Friday, one hour per day. Choose up to five visits per week and customize your schedule in your profile. Each additional dog is $100/month. Requested appointment times are confirmed by Bravo.</Editable><Editable as={Link} contentKey="dogtrainingpage-6" canEditLink canEditText className="button" to="/portal?program=training">Request dog training</Editable><Editable as="p" contentKey="dogtrainingpage-7"><Editable as="a" contentKey="dogtrainingpage-8" canEditLink canEditText href="tel:+16058242767">Questions? Call (605) 824-2767</Editable></Editable></Editable><img src="/images/obedience-real-world.webp" width="1200" height="800" alt="Trainer and dog owner practicing together outdoors"/></Editable>
    <Editable as="section" contentKey="dogtrainingpage-9" className="panel prose"><Editable as="h2" contentKey="dogtrainingpage-10" canEditText>What would you like to work on?</Editable><Editable as="ul" contentKey="dogtrainingpage-11"><Editable as="li" contentKey="dogtrainingpage-12" canEditText><Editable as="strong" contentKey="dogtrainingpage-13" canEditText>Puppy foundations:</Editable> introduce structure, communication and everyday routines.</Editable><Editable as="li" contentKey="dogtrainingpage-14" canEditText><Editable as="strong" contentKey="dogtrainingpage-15" canEditText>Basic and advanced obedience:</Editable> practice clearer cues and more dependable responses.</Editable><Editable as="li" contentKey="dogtrainingpage-16" canEditText><Editable as="strong" contentKey="dogtrainingpage-17" canEditText>Everyday behavior:</Editable> work on walks, doorways, distractions and boundaries.</Editable><Editable as="li" contentKey="dogtrainingpage-18" canEditText><Editable as="strong" contentKey="dogtrainingpage-19" canEditText>Specialist goals:</Editable> talk with Bravo about working-dog and service-dog training needs.</Editable></Editable><Editable as="p" contentKey="dogtrainingpage-20">If aggression or difficult handling is the main concern, start with our <Editable as={Link} contentKey="dogtrainingpage-21" canEditLink canEditText to="/behavior-assessment">two-trainer behavior assessment</Editable> so the team can discuss the right next steps.</Editable></Editable>
    <Editable as="section" contentKey="dogtrainingpage-22" className="panel prose"><Editable as="h2" contentKey="dogtrainingpage-23" canEditText>Getting started is simple.</Editable><Editable as="ol" contentKey="dogtrainingpage-24"><Editable as="li" contentKey="dogtrainingpage-25" canEditText>Choose professional training and tell us about your dog and goals.</Editable><Editable as="li" contentKey="dogtrainingpage-26" canEditText>Review the current membership price and available appointment times.</Editable><Editable as="li" contentKey="dogtrainingpage-27" canEditText>Save your request. Bravo will confirm the visit and trainer assignment.</Editable></Editable><Editable as="p" contentKey="dogtrainingpage-28">Saving a request does not charge your card. The booking summary shows current pricing for the dogs covered. Existing members can use <Editable as={Link} contentKey="dogtrainingpage-29" canEditLink canEditText to="/schedule">My schedule</Editable> to manage covered visits, or ask the team to help.</Editable></Editable>
    <Editable as="section" contentKey="dogtrainingpage-30" className="panel prose service-questions"><Editable as="h2" contentKey="dogtrainingpage-31" canEditText>Dog training questions.</Editable><Editable as="details" contentKey="dogtrainingpage-32"><Editable as="summary" contentKey="dogtrainingpage-33" canEditText>Do you come to my home?</Editable><Editable as="p" contentKey="dogtrainingpage-34" canEditText>Yes. Bravo provides private mobile training in Aberdeen, South Dakota. Add your visit address when arranging training. Call the team to confirm service for your location.</Editable></Editable><Editable as="details" contentKey="dogtrainingpage-35"><Editable as="summary" contentKey="dogtrainingpage-36" canEditText>Can I include more than one dog?</Editable><Editable as="p" contentKey="dogtrainingpage-37" canEditText>Yes. Select the number of dogs in your booking request. The summary shows the first-dog price and the cost for each additional dog before checkout.</Editable></Editable><Editable as="details" contentKey="dogtrainingpage-38"><Editable as="summary" contentKey="dogtrainingpage-39" canEditText>How do I choose days and times?</Editable><Editable as="p" contentKey="dogtrainingpage-40" canEditText>Use the calendar to select your dates, then apply a time to the selected days. You can change an individual date separately. Available times follow your trainer’s schedule.</Editable></Editable><Editable as="details" contentKey="dogtrainingpage-41"><Editable as="summary" contentKey="dogtrainingpage-42" canEditText>Do you offer dog walking too?</Editable><Editable as="p" contentKey="dogtrainingpage-43">Yes. <Editable as={Link} contentKey="dogtrainingpage-44" canEditLink canEditText to="/dog-walking">Bravo dog walking</Editable> is a separate service with 30-minute walks and per-dog pricing.</Editable></Editable></Editable>
    <TrainingFacts/>
    <Editable as="p" contentKey="dogtrainingpage-45"><Editable as={Link} contentKey="dogtrainingpage-46" canEditLink canEditText className="inline-link" to="/contact">Talk with Bravo about your dog →</Editable></Editable>
  </Page>;
}
