import { Link } from 'react-router-dom';
import { AppointmentNotice, Page } from './ui';

export default function DogTrainingPage() {
  return <Page title="Dog training in Aberdeen, SD." eyebrow="PRIVATE TRAINING · WE COME TO YOU" intro="Build everyday skills at home and in the places your dog needs them. Bravo K9 Solutions brings private mobile training to you in Aberdeen, South Dakota.">
    <section className="service-overview panel"><div><h2>A plan for your dog and your daily life.</h2><p>Start with the things you want to improve: calmer walks, clearer boundaries, puppy routines or more dependable obedience. Your trainer learns about your dog, your home and your goals, then helps you practice a consistent approach.</p><p>Sessions are private. You work with the Bravo team in your dog’s everyday environment, with practical guidance you can use between visits.</p><Link className="button" to="/portal?program=training">Request dog training</Link><p><a href="tel:+16058242767">Questions? Call (605) 824-2767</a></p></div><img src="/images/obedience-real-world.webp" width="1200" height="800" alt="Trainer and dog owner practicing together outdoors"/></section>
    <section className="panel prose"><h2>What would you like to work on?</h2><ul><li><strong>Puppy foundations:</strong> introduce structure, communication and everyday routines.</li><li><strong>Basic and advanced obedience:</strong> practice clearer cues and more dependable responses.</li><li><strong>Everyday behavior:</strong> work on walks, doorways, distractions and boundaries.</li><li><strong>Specialist goals:</strong> talk with Bravo about working-dog and service-dog training needs.</li></ul><p>If aggression or difficult handling is the main concern, start with our <Link to="/behavior-assessment">two-trainer behavior assessment</Link> so the team can discuss the right next steps.</p></section>
    <section className="panel prose"><h2>Getting started is simple.</h2><ol><li>Choose professional training and tell us about your dog and goals.</li><li>Review the current membership price and available appointment times.</li><li>Save your request. Bravo will confirm the visit and trainer assignment.</li></ol><p>Saving a request does not charge your card. The booking summary shows current pricing for the dogs covered. Existing members can use <Link to="/schedule">My schedule</Link> to manage covered visits, or ask the team to help.</p></section>
    <section className="panel prose service-questions"><h2>Dog training questions.</h2><details><summary>Do you come to my home?</summary><p>Yes. Bravo provides private mobile training in Aberdeen, South Dakota. Add your visit address when arranging training. Call the team to confirm service for your location.</p></details><details><summary>Can I include more than one dog?</summary><p>Yes. Select the number of dogs in your booking request. The summary shows the first-dog price and the cost for each additional dog before checkout.</p></details><details><summary>How do I choose days and times?</summary><p>Use the calendar to select your dates, then apply a time to the selected days. You can change an individual date separately. Available times follow your trainer’s schedule.</p></details><details><summary>Do you offer dog walking too?</summary><p>Yes. <Link to="/dog-walking">Bravo dog walking</Link> is a separate service with 30-minute walks and per-dog pricing.</p></details></section>
    <AppointmentNotice/>
    <p><Link className="inline-link" to="/contact">Talk with Bravo about your dog →</Link></p>
  </Page>;
}
