import HeroPhotoCarousel from './HeroPhotoCarousel';
import TrainingFacts from './TrainingFacts';
import TrainerIntroduction from './TrainerIntroduction';
import { Editable } from './SiteContent';
import Link from './Link';
import TrainerScheduleCard, { useLiveTrainerSchedules } from './TrainerScheduleCard';
import './trainer-schedules.css';
import './home-backdrop.css';
import { useEffect, useState } from 'react';
import { api } from './api';
import { Header, Footer } from './ui';
import ServiceIcon from './ServiceIcon';
import { useBravo } from './context';
import { SERVICES, money } from '../../shared/catalog';
import { HOME_HERO_SOURCE, HOME_HERO_ALT, HOME_HERO_KEY } from '../../shared/home-hero.js';
import { framingStyle } from '../../shared/site-images.js';
import { getSiteImages } from './site-image-state.js';
import ProofVideoCarousel from './ProofVideoCarousel';
import HomeBanner from './HomeBanner';

const secondary = ['walking', 'aggression'];
const serviceDetails: Record<string, { label: string; text: string; features: string[] }> = {
  training: { label: 'BUILD A BETTER EVERYDAY', text: 'Calmer walks. Clearer boundaries. A dog you can depend on.', features: ['Private training at your home', 'One hour per day · Monday–Friday', 'Customize your schedule in your profile'] },
  walking: { label: '30 MINUTES. REAL MOVEMENT.', text: 'Reliable dog walking from the Bravo team, scheduled around your day.', features: ['$25 per dog', '30-minute walk', 'Simple multi-dog pricing'] },
  aggression: { label: 'START WITH UNDERSTANDING', text: 'A focused first step for dogs who need a more considered approach.', features: ['Initial assessment with two trainers', 'Behavior and handling review', 'Discuss the next steps with Bravo'] },
  online: { label: 'TRAIN BETWEEN SESSIONS', text: 'Private member lessons from the Bravo team, available when you need them.', features: ['Trainer-uploaded video lessons', 'Captions and written transcripts', 'Learn at your own pace'] },
};
export default function Home() {
  const [hero] = useState(() => getSiteImages()[HOME_HERO_KEY]);
  const { config } = useBravo();
  const liveSchedules = useLiveTrainerSchedules();
  const catalog = config?.services?.length ? config.services : SERVICES;
  const training = catalog.find(service => service.id === 'training');
  const [team, setTeam] = useState<Array<{id: string; name: string; role: string; title: string; bio: string}>>([]);
  const [reviews, setReviews] = useState<{reviews: Array<{_id: string; authorName: string; rating: number; body: string}>; average: number; count: number}>({ reviews: [], average: 0, count: 0 });
  useEffect(() => { api('/team').then(people => setTeam(people.team)).catch(() => {}); api('/reviews').then(feedback => setReviews(feedback)).catch(() => {}); }, []);
  const portraits: Record<string, string> = { 'David Northrop': 'david-northrop', 'Ashley Northrop': 'ashley-northrop', 'Ashley Leverock': 'ashley-leverock', 'Janet Hughes': 'janet-hughes' };
  return <Editable as="div" contentKey="home-1" className="bravo-home"><div className="home-prairie-backdrop" aria-hidden="true"/><Header/>
    <Editable as="main" contentKey="home-2" id="main-content" tabIndex={-1}>
      <Editable as="section" contentKey="home-3" className="home-hero home-hero-authentic" aria-labelledby="home-title">
        <HeroPhotoCarousel><img className="home-hero-image" src={hero?.src || HOME_HERO_SOURCE} width="828" height="1121" loading="eager" fetchPriority="high" alt={hero?.framed ? hero.alt : HOME_HERO_ALT} style={hero?.framed ? framingStyle(hero) : undefined} data-site-image-original={HOME_HERO_SOURCE} data-site-image-original-alt={HOME_HERO_ALT} data-site-media-original-styles='{"objectFit":"","objectPosition":"","transform":"","transformOrigin":"","clipPath":""}'/></HeroPhotoCarousel>
        <Editable as="div" contentKey="home-4" className="home-hero-shade"/>
        <Editable as="div" contentKey="home-5" className="shell home-hero-inner"><Editable as="div" contentKey="home-6" className="home-hero-copy">
          <Editable as="p" contentKey="home-7" canEditText className="eyebrow">ABERDEEN, SOUTH DAKOTA <Editable as="span" contentKey="home-8" canEditText> / </Editable> MOBILE DOG TRAINING</Editable>
          <Editable as="h1" contentKey="home-9" canEditText id="home-title">Meet your local<br/><Editable as="em" contentKey="home-10" canEditText>training team.</Editable></Editable>
          <Editable as="p" contentKey="home-11" canEditText className="home-intro">We’re David and Ashley, the Bravo training team in Aberdeen, South Dakota. We work with you and your dog at home. Tell us what’s difficult right now, and let’s find a place to start.</Editable>
          <Editable as="div" contentKey="home-12" className="home-hero-actions"><Editable as={Link} contentKey="home-13" canEditLink canEditText className="button" href="/portal?program=training">Start private training <span aria-hidden="true">→</span></Editable><Editable as="a" contentKey="home-15" canEditLink canEditText className="button button-ghost" href="#reviews">See client results</Editable></Editable>
          <Editable as="div" contentKey="home-16" className="hero-service-note"><Editable as="span" contentKey="home-17" canEditText>PRIVATE SESSIONS</Editable><Editable as="span" contentKey="home-18" canEditText>WE COME TO YOU</Editable><Editable as="span" contentKey="home-19" canEditText>PROFESSIONAL TRAINERS</Editable></Editable>
        </Editable><Editable as="div" contentKey="home-20" className="hero-field-note"><Editable as="span" contentKey="home-21" canEditText>AT HOME. IN EVERYDAY LIFE.</Editable><Editable as="p" contentKey="home-22" canEditText>Calmer.<br/>Clearer.<br/><Editable as="em" contentKey="home-23" canEditText>Together.</Editable></Editable></Editable></Editable>
      </Editable>
      <HomeBanner/>
      <Editable as="div" contentKey="home-24" className="home-service-strip"><Editable as="div" contentKey="home-25" className="shell"><Editable as="p" contentKey="home-26" canEditText><Editable as="strong" contentKey="home-27" canEditText>Not sure where to start?</Editable><Editable as="span" contentKey="home-28" canEditText>Tell us what life with your dog is like. We’ll help you choose.</Editable></Editable><Editable as="a" contentKey="home-29" canEditLink canEditText href="tel:+16058242767">Talk to Bravo <Editable as="span" contentKey="home-30" canEditText>(605) 824-2767</Editable></Editable></Editable></Editable>
      <Editable as="div" contentKey="home-31" className="shell site-media-tools-slot site-media-tools-slot--home" data-site-media-tools=""/>
      <Editable as="section" contentKey="home-32" className="home-section shell home-proof" id="reviews" aria-labelledby="reviews-title">
        <Editable as="div" contentKey="home-33" className="home-section-heading"><Editable as="div" contentKey="home-34"><Editable as="p" contentKey="home-35" canEditText className="eyebrow">01 / PROOF BEFORE PROMISES</Editable><Editable as="h2" contentKey="home-36" canEditText id="reviews-title">See the work.<br/><Editable as="em" contentKey="home-37" canEditText>Meet your team.</Editable></Editable></Editable><Editable as="p" contentKey="home-38">{reviews.count > 0 && <><Editable as="strong" contentKey="home-39">{reviews.average} out of 5</Editable> from {reviews.count} verified Bravo account {reviews.count === 1 ? 'review' : 'reviews'}.</>}</Editable></Editable>
        <details className="home-why"><summary>Why train with Bravo?</summary><Editable as="div" contentKey="home-40" className="home-proof-grid" aria-label="Why clients choose Bravo"><Editable as="article" contentKey="home-41"><Editable as="strong" contentKey="home-42" canEditText>PRIVATE</Editable><Editable as="span" contentKey="home-43" canEditText>One trainer, one household, and a plan built around your dog.</Editable></Editable><Editable as="article" contentKey="home-44"><Editable as="strong" contentKey="home-45" canEditText>FULL-TIME</Editable><Editable as="span" contentKey="home-46" canEditText>Professional Bravo trainers serving clients in and around Aberdeen.</Editable></Editable><Editable as="article" contentKey="home-47"><Editable as="strong" contentKey="home-48" canEditText>MOBILE</Editable><Editable as="span" contentKey="home-49" canEditText>Training where everyday behavior actually happens—we come to you.</Editable></Editable><Editable as="article" contentKey="home-50"><Editable as="strong" contentKey="home-51" canEditText>EVERYDAY LIFE</Editable><Editable as="span" contentKey="home-52" canEditText>Calmer walks, clearer routines, and practical help at home.</Editable></Editable></Editable></details>
        <ProofVideoCarousel/>
        {reviews.reviews.length > 0 && <Editable as="div" contentKey="home-53" className="review-grid home-proof-reviews">{reviews.reviews.slice(0, 3).map(review => <Editable as="article" contentKey="home-54" key={review._id} className="panel"><Editable as="div" contentKey="home-55" className="review-stars" role="img" aria-label={`${review.rating} out of 5 stars`}><span aria-hidden="true">{'★'.repeat(review.rating)}{'☆'.repeat(5 - review.rating)}</span></Editable><Editable as="p" contentKey="home-57">“{review.body}”</Editable><Editable as="strong" contentKey="home-58">{review.authorName}</Editable><Editable as="small" contentKey="home-59" canEditText>Verified Bravo account</Editable></Editable>)}</Editable>}
        {team.length > 0 && <Editable as="div" contentKey="home-60" className="home-proof-team"><Editable as="p" contentKey="home-61" canEditText className="eyebrow">THE PROFESSIONALS BEHIND THE WORK</Editable><Editable as="div" contentKey="home-62">{team.slice(0, 3).map(person => <Editable as="span" contentKey="home-63" key={person.id}><Editable as="strong" contentKey="home-64">{person.name}</Editable><Editable as="small" contentKey="home-65">{person.title}</Editable></Editable>)}</Editable></Editable>}
        <Editable as="div" contentKey="home-66" className="home-proof-links"><Editable as="a" contentKey="home-67" canEditLink canEditText className="inline-link" href="#team">Meet the trainers →</Editable><Editable as={Link} contentKey="home-68" canEditLink canEditText className="inline-link" href="/account#your-review">Share your experience →</Editable></Editable>
      </Editable>
      <Editable as="section" contentKey="home-69" className="home-section shell" id="training" aria-labelledby="program-title">
        <Editable as="div" contentKey="home-70" className="home-section-heading"><Editable as="div" contentKey="home-71"><Editable as="p" contentKey="home-72" canEditText className="eyebrow">02 / START HERE</Editable><Editable as="h2" contentKey="home-73" canEditText id="program-title">Private training.<br/><Editable as="em" contentKey="home-74" canEditText>One clear first step.</Editable></Editable></Editable><Editable as="p" contentKey="home-75" canEditText>Start with your dog’s everyday challenges. We’ll meet you at home and agree on the next steps together.</Editable></Editable>
        {training && training.enabled !== false && <Editable as="article" contentKey="home-76" className="home-training-offer"><Editable as="div" contentKey="home-77" className="home-training-main"><ServiceIcon service="training"/><Editable as="p" contentKey="home-78" canEditText className="eyebrow">{serviceDetails.training.label}</Editable><Editable as="h3" contentKey="home-79">{training.name}</Editable><Editable as="p" contentKey="home-80" canEditText>{serviceDetails.training.text}</Editable><Editable as="div" contentKey="home-81" className="home-price">{money(training.cents)}<Editable as="span" contentKey="home-82" canEditText>/ month for one dog</Editable></Editable><Editable as="ul" contentKey="home-83">{serviceDetails.training.features.map(feature => <Editable as="li" contentKey="home-84" key={feature}>{feature}</Editable>)}</Editable><Editable as="div" contentKey="home-85" className="home-training-actions"><Editable as={Link} contentKey="home-86" canEditLink canEditText className="button" href="/portal?program=training">Start with private training <span aria-hidden="true">→</span></Editable><Editable as={Link} contentKey="home-88" canEditLink canEditText className="home-text-link" href="/dog-training">See how training works <span aria-hidden="true">↗</span></Editable></Editable></Editable><Editable as="aside" contentKey="home-90" aria-label="Who private training is for"><Editable as="p" contentKey="home-91" canEditText className="eyebrow">A STRONG START FOR</Editable><Editable as="ul" contentKey="home-92"><Editable as="li" contentKey="home-93" canEditText>Puppy foundations and everyday obedience</Editable><Editable as="li" contentKey="home-94" canEditText>Leash behavior, boundaries, and calm decisions</Editable><Editable as="li" contentKey="home-95" canEditText>Owners who want private, practical instruction</Editable></Editable><Editable as="p" contentKey="home-96" canEditText>Each additional dog is $100/month. Your monthly membership includes up to five one-hour visits per week, Monday–Friday. Choose your days and times in your profile; Bravo confirms requested visits. No automatic renewal.</Editable></Editable></Editable>}
        <TrainingFacts/>
        <Editable as="div" contentKey="home-97" className="home-secondary-heading"><Editable as="div" contentKey="home-98"><Editable as="p" contentKey="home-99" canEditText className="eyebrow">NEED A DIFFERENT START?</Editable><Editable as="h3" contentKey="home-100" canEditText>Choose the situation that fits.</Editable></Editable><Editable as="p" contentKey="home-101" canEditText>Need regular walks or help with aggression? Start here.</Editable></Editable>
        <Editable as="div" contentKey="home-102" className="home-secondary-services">{secondary.map(id => { const service = catalog.find(s => s.id === id); const detail = serviceDetails[id]; return service && service.enabled !== false ? <Editable as="article" contentKey="home-103" key={id}><ServiceIcon service={id}/><Editable as="div" contentKey="home-104"><Editable as="p" contentKey={`home-secondary-${id}-label`} canEditText className="eyebrow">{detail.label}</Editable><Editable as="h3" contentKey="home-106">{service.name}</Editable><Editable as="p" contentKey={`home-secondary-${id}-text`} canEditText>{detail.text}</Editable></Editable><Editable as="div" contentKey="home-108" className="home-secondary-action"><Editable as="strong" contentKey="home-109">{money(service.cents)} <Editable as="small" contentKey="home-110">{service.interval === 'walk' ? '/ dog' : 'initial intake'}</Editable></Editable><Editable as={Link} contentKey="home-111" canEditText className="home-text-link" href={id === 'walking' ? '/dog-walking' : '/behavior-assessment'}>Explore <span aria-hidden="true">↗</span></Editable></Editable></Editable> : null; })}</Editable>
      </Editable>
      <Editable as="section" contentKey="home-113" className="home-method shell" id="method" aria-labelledby="method-title"><Editable as="div" contentKey="home-114" className="home-method-photo"><img src="/images/obedience-real-world.webp" width="1200" height="800" loading="lazy" alt="Trainer and dog owner working together outdoors"/><Editable as="span" contentKey="home-115" canEditText>TRAIN FOR THE LIFE YOU ACTUALLY LIVE.</Editable></Editable><Editable as="div" contentKey="home-116" className="home-method-copy"><Editable as="p" contentKey="home-117" canEditText className="eyebrow">03 / THE BRAVO METHOD</Editable><Editable as="h2" contentKey="home-118" canEditText id="method-title">Clear structure.<br/><Editable as="em" contentKey="home-119" canEditText>Lasting trust.</Editable></Editable><Editable as="p" contentKey="home-120" canEditText>Help your dog handle the moments that matter: a walk, a visitor at the door, or settling down at home. Your trainer works with you in those everyday situations.</Editable><Editable as="ol" contentKey="home-121" className="home-process"><Editable as="li" contentKey="home-122"><Editable as="span" contentKey="home-123" canEditText>01</Editable><Editable as="div" contentKey="home-124"><Editable as="h3" contentKey="home-125" canEditText>Meet the dog.</Editable><Editable as="p" contentKey="home-126" canEditText>We come to you, learn the full picture, and see your dog in its own environment.</Editable></Editable></Editable><Editable as="li" contentKey="home-127"><Editable as="span" contentKey="home-128" canEditText>02</Editable><Editable as="div" contentKey="home-129"><Editable as="h3" contentKey="home-130" canEditText>Build the plan.</Editable><Editable as="p" contentKey="home-131" canEditText>Your trainer shapes the work around your dog, your routines, and your goals.</Editable></Editable></Editable><Editable as="li" contentKey="home-132"><Editable as="span" contentKey="home-133" canEditText>03</Editable><Editable as="div" contentKey="home-134"><Editable as="h3" contentKey="home-135" canEditText>Make it hold.</Editable><Editable as="p" contentKey="home-136" canEditText>Bring that structure into walks, doorways, distractions, and everyday decisions.</Editable></Editable></Editable></Editable></Editable></Editable>
      <details className="shell home-more"><summary>Specialist and working-dog programs</summary><Editable as="section" contentKey="home-137" className="home-section shell" aria-labelledby="specialties-title"><Editable as="div" contentKey="home-138" className="home-section-heading"><Editable as="div" contentKey="home-139"><Editable as="p" contentKey="home-140" canEditText className="eyebrow">PURPOSE BEYOND OBEDIENCE</Editable><Editable as="h2" contentKey="home-141" canEditText id="specialties-title">Different work.<br/><Editable as="em" contentKey="home-142" canEditText>The same standard.</Editable></Editable></Editable><Editable as={Link} contentKey="home-143" canEditLink canEditText className="home-text-link" href="/contact">Discuss a specialist program <span aria-hidden="true">↗</span></Editable></Editable><Editable as="div" contentKey="home-145" className="home-specialties">{[
        ['Job-specific training', 'Focused foundations shaped around a defined working goal.'],
        ['Service dog foundations', 'Public-access manners, task foundations, and handler confidence.'],
        ['Protection & working K9s', 'Control, sound nerves, clear outs, and responsible handling.'],
        ['Tracking & search', 'Scent foundations, accuracy, and a stronger handler partnership.'],
      ].map(([title, copy], index) => <Editable as="article" contentKey="home-146" key={title}><Editable as="span" contentKey="home-147" className="eyebrow">0{index + 1}</Editable><Editable as="h3" contentKey={`home-specialty-${index}-title`} canEditText>{title}</Editable><Editable as="p" contentKey={`home-specialty-${index}-copy`} canEditText>{copy}</Editable></Editable>)}</Editable></Editable></details>
      <Editable as="section" contentKey="home-150" className="home-team-section" id="team"><Editable as="div" contentKey="home-151" className="shell"><Editable as="div" contentKey="home-152" className="home-section-heading"><Editable as="div" contentKey="home-153"><Editable as="p" contentKey="home-154" canEditText className="eyebrow">04 / YOUR BRAVO TEAM</Editable><Editable as="h2" contentKey="home-155" canEditText>People behind<br/><Editable as="em" contentKey="home-156" canEditText>the progress.</Editable></Editable></Editable><Editable as="p" contentKey="home-157" canEditText>Meet the people who will work with you and your dog.</Editable></Editable><Editable as="div" contentKey="home-158" className="home-team-grid">{team.map(person => <Editable as="article" contentKey="home-159" key={person.id}><Editable as="div" contentKey="home-160" className="home-portrait"><img src={`/images/${portraits[person.name] || 'bravo-logo-small'}.webp`} width="1000" height="1400" loading="lazy" alt={`${person.name}, ${person.role}`}/></Editable><Editable as="div" contentKey="home-161" className="home-person"><Editable as="p" contentKey="home-162" className="eyebrow">{person.role === "owner" ? "OWNER" : "STAFF"}</Editable><Editable as="h3" contentKey="home-163">{person.name}</Editable><Editable as="p" contentKey="home-164">{person.title}</Editable><TrainerIntroduction person={person}/><details className="home-availability"><summary>View {person.name.split(' ')[0]}’s working hours</summary><TrainerScheduleCard person={person} live={liveSchedules}/></details><Editable as={Link} contentKey="home-166" canEditLink canEditText className="inline-link" href="/contact">Contact trainer →</Editable></Editable></Editable>)}</Editable></Editable></Editable>
      <details className="shell home-more"><summary>Explore online training lessons</summary><Editable as="section" contentKey="home-167" className="home-section shell home-learning"><Editable as="div" contentKey="home-168"><Editable as="p" contentKey="home-169" canEditText className="eyebrow">KEEP LEARNING WITH BRAVO</Editable><Editable as="h2" contentKey="home-170" canEditText>The work behind<br/><Editable as="em" contentKey="home-171" canEditText>the progress.</Editable></Editable><Editable as="p" contentKey="home-172" canEditText>Members can learn from staff-published video lessons with captions and readable transcripts—at home and at their own pace.</Editable><Editable as="div" contentKey="home-173" className="home-learning-price"><Editable as="strong" contentKey="home-174">{money(catalog.find(service => service.id === 'online')?.cents ?? 5000)} <Editable as="span" contentKey="home-175" canEditText>/ month online</Editable></Editable><Editable as="span" contentKey="home-176" canEditText>A focused library built by your trainers.</Editable></Editable><Editable as={Link} contentKey="home-177" canEditLink canEditText className="button button-ghost" href="/learn">Explore the lesson catalog <span aria-hidden="true">↗</span></Editable></Editable><Editable as={Link} contentKey="home-179" canEditLink className="home-lesson-preview" href="/learn"><img src="/images/training-education.webp" width="1600" height="900" loading="lazy" alt="Handler demonstrating a lesson with a Belgian Malinois"/><Editable as="div" contentKey="home-180"><Editable as="span" contentKey="home-181" canEditText className="badge">MEMBER LEARNING</Editable><Editable as="h3" contentKey="home-182" canEditText>Leash pressure:<br/>timing over force.</Editable><Editable as="span" contentKey="home-183" canEditText className="home-text-link">Explore training topics <span aria-hidden="true">↗</span></Editable></Editable></Editable></Editable></details>
      <Editable as="section" contentKey="home-185" className="home-close"><Editable as="div" contentKey="home-186" className="shell"><Editable as="div" contentKey="home-187"><Editable as="p" contentKey="home-188" canEditText className="eyebrow">THE FIRST STEP IS SIMPLE.</Editable><Editable as="h2" contentKey="home-189" canEditText>Let’s meet<br/><Editable as="em" contentKey="home-190" canEditText>your dog.</Editable></Editable></Editable><Editable as="div" contentKey="home-191"><Editable as="p" contentKey="home-192" canEditText>Tell us about your dog. Choose a first visit. We’ll take it from there.</Editable><Editable as={Link} contentKey="home-193" canEditLink canEditText className="button" href="/portal">Request your first visit <span aria-hidden="true">↗</span></Editable><Editable as="a" contentKey="home-195" canEditLink canEditText href="tel:+16058242767">Prefer to talk? (605) 824-2767</Editable></Editable></Editable></Editable>
    </Editable><Footer/>
  </Editable>;
}
