import { Editable } from './SiteContent';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from './api';
import { money } from '../../shared/catalog';
import { useBravo } from './context';
import { Page, Notice } from './ui';
export default function LearnPage() {
  const { user, services, config, membership, refreshUser } = useBravo();
  const [lessons, setLessons] = useState([]), [filter, setFilter] = useState('All'), [selected, setSelected] = useState(null), [transcript, setTranscript] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(true);
  const member = !!user && (['staff', 'owner'].includes(user.role) || services.includes('online') || membership?.onlineAccess === true);
  useEffect(() => { api('/lessons').then(data => setLessons(data.lessons)).catch(e => setError(e.message)).finally(() => setLoading(false)); refreshUser().catch(() => {}); }, [refreshUser]);
  useEffect(() => { if (selected) document.getElementById('current-lesson')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }, [selected]);
  useEffect(() => { if (!member) { setSelected(null); setTranscript(''); } }, [member, user?.id]);
  async function open(lesson) {
    setError(''); setSelected(null); setTranscript('');
    try { const data = await api(`/lessons/${lesson._id}/transcript`); setTranscript(data.transcript); setSelected(lesson); }
    catch (e) { setError(e.message); }
  }
  return <Page className="learning-page" title="Learn the Bravo way." eyebrow={membership?.manual ? 'ONLINE TRAINING · MEMBER ACCESS ACTIVE' : `ONLINE TRAINING · ${money(config?.services?.find(service => service.id === 'online')?.cents ?? 5000)} / MONTH`} intro="Practical lessons from the Bravo team. Browse the topics below; active Member access unlocks published videos and transcripts."><Editable as="div" contentKey="learnpage-1" className="learn-banner"><img src="/images/training-education.webp" width="1600" height="900" alt="Bravo training lesson with a handler and Belgian Malinois"/><Editable as="div" contentKey="learnpage-2"><Editable as="p" contentKey="learnpage-3" canEditText className="kicker gold">REAL WORK. CLEAR EXPLANATIONS.</Editable><Editable as="h2" contentKey="learnpage-4" canEditText>Better handlers.<br/>Better dogs.</Editable><Editable as="p" contentKey="learnpage-5" canEditText>Video lessons, synchronized captions, and readable transcripts in one place.</Editable><Editable as={Link} contentKey="learnpage-6" className="button" to={member ? '/account' : '/portal?program=online'}>{member ? 'Your membership' : 'Explore membership'}</Editable></Editable></Editable><Notice error>{error}</Notice>
    {membership?.manual && <Notice>Your Member access was activated by Bravo. No additional online subscription is needed to watch published lessons.</Notice>}
    {!loading && !lessons.some(l => l.published) && <Notice>The lesson library is being prepared. These are upcoming topics—not playable videos. Online enrollment stays closed until published lessons are ready.</Notice>}
    {selected && <Editable as="section" contentKey="learnpage-7" className="panel lesson-player" id="current-lesson"><Editable as="button" contentKey="learnpage-8" canEditText type="button" className="button button-ghost" onClick={()=>{setSelected(null);setTranscript('');document.getElementById('library')?.scrollIntoView({behavior:'smooth'});}}>Back to lessons</Editable><Editable as="h2" contentKey="learnpage-9">{selected.title}</Editable><video key={selected._id} controls preload="metadata" controlsList="nodownload" onError={() => setError('This video could not load. Please try again or contact Bravo.')}><source src={`/api/lessons/${selected._id}/video`}/><track kind="captions" src={`/api/lessons/${selected._id}/captions`} srcLang="en" label="English" default/>Your browser does not support this video. Read the transcript below.</video><Editable as="details" contentKey="learnpage-10" open><Editable as="summary" contentKey="learnpage-11" canEditText>Read transcript</Editable><Editable as="p" contentKey="learnpage-12" className="transcript">{transcript}</Editable></Editable></Editable>}
    <Editable as="section" contentKey="learnpage-13" id="library"><Editable as="div" contentKey="learnpage-14" className="section-label"><Editable as="h2" contentKey="learnpage-15" canEditText>The lesson catalog.</Editable><Editable as="label" contentKey="learnpage-16">Filter by topic<select value={filter} onChange={e => setFilter(e.target.value)}>{['All', ...new Set(lessons.map(l => l.category))].map(c => <option key={c}>{c}</option>)}</select></Editable></Editable>{loading ? <Editable as="p" contentKey="learnpage-17" canEditText role="status">Loading the library…</Editable> : <Editable as="div" contentKey="learnpage-18" className="member-lesson-grid">{lessons.filter(l => filter === 'All' || l.category === filter).map(lesson => <Editable as="article" contentKey="learnpage-19" className="member-lesson" key={lesson._id}><img src={lesson.image} width="900" height="600" alt="" loading="lazy"/><Editable as="div" contentKey="learnpage-20"><Editable as="span" contentKey="learnpage-21" className="kicker gold">{lesson.category}</Editable><Editable as="h3" contentKey="learnpage-22">{lesson.title}</Editable><Editable as="p" contentKey="learnpage-23">With {lesson.instructor}</Editable>{!lesson.published ? <Editable as="span" contentKey="learnpage-24" canEditText className="badge">Coming soon</Editable> : member ? <Editable as="button" contentKey="learnpage-25" canEditText className="button button-small" onClick={() => open(lesson)}>Watch lesson</Editable> : <Editable as={Link} contentKey="learnpage-26" canEditText className="inline-link" to={user ? '/portal?program=online' : '/account'}>Member access required →</Editable>}</Editable></Editable>)}</Editable>}</Editable>
    <Editable as="section" contentKey="learnpage-27" id="accessible-media" className="panel prose"><Editable as="h2" contentKey="learnpage-28" canEditText>Accessible learning.</Editable><Editable as="p" contentKey="learnpage-29" canEditText>Published lessons must include English captions and a written transcript. Use the CC control for captions, or read the transcript without playing audio. Contact Bravo if you need another format.</Editable></Editable>
  </Page>;
}
