import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from './api';
import { useBravo } from './context';
import { Page, Notice } from './ui';
import { Editable } from './SiteContent';
import { lessonLibraryVisible } from '../../shared/lesson-library';
import LessonOffers from './LessonOffers';
export default function LearnPage() {
  const { user, services, config, membership, refreshUser } = useBravo();
  const [lessons,setLessons]=useState([]),[sections,setSections]=useState([]),[filter,setFilter]=useState('All'),[selected,setSelected]=useState(null),[transcript,setTranscript]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const visible=lessonLibraryVisible(config,user), editor=user?.role==='owner';
  const member=!!user && (['staff','owner'].includes(user.role)||services.includes('online')||membership?.onlineAccess===true);
  useEffect(()=>{let active=true;setError('');setSelected(null);setTranscript('');setLessons([]);setSections([]);if(!visible){setLoading(false);return;}setLoading(true);api('/lessons').then(data=>{if(active){setLessons(data.lessons);setSections(data.sections||[]);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[visible,user?.id]);
  useEffect(()=>{refreshUser().catch(()=>{});},[refreshUser]);
  useEffect(()=>{if(selected)document.getElementById('current-lesson')?.scrollIntoView({behavior:'smooth',block:'start'});},[selected]);
  useEffect(()=>{if(!member){setSelected(null);setTranscript('');}},[member,user?.id]);
  async function open(lesson){setError('');setSelected(null);setTranscript('');try{const data=await api(`/lessons/${lesson._id}/transcript`);setTranscript(data.transcript);setSelected(lesson);}catch(e){setError(e.message);}}
  if(!visible)return <Page title="This page is unavailable."><p><Link to="/">Return to Bravo</Link></p></Page>;
  const groups=[...sections,{_id:'',title:'General lessons',description:''}];
  return <Page className="learning-page" title="Learn the Bravo way." eyebrow={editor&&!config?.lessonLibrary?.open?'PRIVATE LIBRARY PREVIEW':'BRAVO ONLINE LESSONS'} intro="Practical lessons from David and Ashley. Follow the sections at your own pace.">
    {editor&&<Notice><Link to="/admin?tab=lessons">Open Lesson studio →</Link>{!config?.lessonLibrary?.open&&<p>Only owners and administrators can see this library while it is closed.</p>}</Notice>}
    <Editable as="div" contentKey="learnpage-1" className="learn-banner"><img src="/images/training-education.webp" width="1600" height="900" alt="Bravo training lesson with a handler and Belgian Malinois"/><Editable as="div" contentKey="learnpage-2"><Editable as="h2" contentKey="learnpage-4" canEditText>Better handlers.<br/>Better dogs.</Editable><Editable as="p" contentKey="learnpage-5" canEditText>Video lessons, helpful photos, and clear written instructions from your trainers.</Editable></Editable></Editable>
    <Notice error>{error}</Notice>{(!member||editor)&&<LessonOffers/>}{membership?.manual&&<Notice>Your active Member access includes published lessons. No additional lesson purchase is needed.</Notice>}
    {selected&&<section className="panel lesson-player" id="current-lesson"><button className="button button-ghost" onClick={()=>{setSelected(null);setTranscript('');document.getElementById('library')?.scrollIntoView({behavior:'smooth'});}}>Back to lessons</button><h2>{selected.title}</h2><p>With {selected.instructor}</p><p className="lesson-description">{selected.description}</p>{(selected.format||'video')==='video'&&<video key={selected._id} controls preload="metadata" controlsList="nodownload" poster={selected.image} onError={()=>setError('The video could not load. Please try again or contact Bravo.')}><source src={`/api/lessons/${selected._id}/video`}/><track kind="captions" src={`/api/lessons/${selected._id}/captions`} srcLang="en" label="English" default/></video>}{selected.format==='photo'&&<img src={`/api/lessons/${selected._id}/photo`} alt={selected.photoAlt||selected.title}/>}<details open><summary>{(selected.format||'video')==='video'?'Read transcript':'Read lesson instructions'}</summary><p className="transcript">{transcript}</p></details></section>}
    <section id="library"><div className="section-label"><h2>Your lesson library.</h2><label>Filter by section<select aria-label="Filter by section" value={filter} onChange={e=>setFilter(e.target.value)}><option value="All">All sections</option>{groups.map(section=><option key={section._id} value={section._id}>{section.title}</option>)}</select></label></div>{loading?<p role="status">Loading the library…</p>:!lessons.length?<p>{editor?'Add your first lesson in Lesson studio. You can build and preview it here before opening the library.':'New lessons are being prepared.'}</p>:groups.filter(section=>filter==='All'||filter===section._id).map(section=>{const rows=lessons.filter(lesson=>(lesson.sectionId||'')===section._id);return rows.length?<section className="lesson-section" key={section._id}><h3>{section.title}</h3>{section.description&&<p>{section.description}</p>}<div className="member-lesson-grid">{rows.map(lesson=><article className="member-lesson" key={lesson._id}><img src={lesson.image} width="900" height="600" alt="" loading="lazy"/><div><span className="kicker gold">{lesson.category}</span><h3>{lesson.title}</h3><p>With {lesson.instructor}</p><p className="lesson-description">{lesson.description}</p>{!lesson.published&&<span className="badge">Private draft</span>}{member?<button className="button button-small" onClick={()=>open(lesson)}>{!lesson.published?'Preview lesson':(lesson.format||'video')==='video'?'Watch lesson':'Open lesson'}</button>:<Link className="inline-link" to={user?'/portal?program=online':'/account?next=%2Flearn'}>{user?'Get lesson access →':'Sign in or join →'}</Link>}</div></article>)}</div></section>:null;})}</section>
  </Page>;
}
