import { Editable } from './SiteContent';
export default function TrainingFacts() {
  return <Editable as="div" contentKey="training-facts" className="service-questions">
    <details><Editable as="summary" contentKey="training-question-1" canEditText>What does the monthly program include?</Editable><Editable as="p" contentKey="training-facts-included" canEditText>Private mobile training for the dogs covered by your membership, with one-hour appointment slots. Start with one visit and agree on an ongoing schedule with Bravo. Confirm your planned visit frequency with Bravo before paying. Requested dates depend on availability and confirmation.</Editable></details>
    <details><Editable as="summary" contentKey="training-question-2" canEditText>What happens at the first visit?</Editable><Editable as="p" contentKey="training-facts-first" canEditText>Your trainer meets you and your dog, discusses your goals, and sees the behavior in your everyday environment. You’ll discuss what to work on and how to continue between visits.</Editable></details>
    <details><Editable as="summary" contentKey="training-question-3" canEditText>Can I ask questions between visits?</Editable><Editable as="p" contentKey="training-facts-support" canEditText>Signed-in clients can privately message the Bravo team from their account. For time-sensitive questions, call (605) 824-2767.</Editable></details>
    <details><Editable as="summary" contentKey="training-question-4" canEditText>Will my membership renew automatically?</Editable><Editable as="p" contentKey="training-facts-renewal" canEditText>No. Monthly programs last one month and renew manually. Your account shows your membership dates. Bravo confirms requested visits; saving a request does not charge your card.</Editable></details>
  </Editable>;
}
