import { useEffect, useRef, useState } from 'react';
import { Link, NavLink, useLocation, useNavigate } from 'react-router-dom';
import Brand from './Brand';
import { PAGE_METADATA } from '../../shared/page-metadata';
import './public-services.css';
import BackButton from './BackButton';
import NotificationBell from './NotificationBell';
import { useBravo } from './context';
import './member-access.css';
import './simple-scheduling.css';
export function Header() {
  const { user, signOut, notifications = [] } = useBravo(), { pathname, search } = useLocation(), navigate = useNavigate();
  const [signingOut, setSigningOut] = useState(false), [signOutError, setSignOutError] = useState('');
  async function leave() {
    setSigningOut(true); setSignOutError('');
    try { await signOut(); setMenuOpen(false); navigate('/account', { replace: true }); }
    catch (error) { setSignOutError(error.message || 'Could not sign out. Please try again.'); }
    finally { setSigningOut(false); }
  }
  const [menuOpen, setMenuOpen] = useState(false), menuButton = useRef(null);
  useEffect(() => { setMenuOpen(false); }, [pathname]);
  return <header className="app-header" onKeyDown={e => { if (e.key === 'Escape' && menuOpen) { setMenuOpen(false); menuButton.current?.focus(); } }}><div className="header-inner"><Brand/><button ref={menuButton} className="menu-toggle" aria-expanded={menuOpen} aria-controls="bravo-navigation" onClick={() => setMenuOpen(!menuOpen)}><span className="menu-lines" aria-hidden="true"><i/><i/></span>{menuOpen ? 'Close' : 'Menu'}{notifications.some(item => item.unread) && <span className="menu-notification-count notification-count" aria-label="Unread notifications">{Math.min(99, notifications.filter(item => item.unread).length)}</span>}</button><nav id="bravo-navigation" className={menuOpen ? 'is-open' : ''} onClick={event => { if (event.target.closest('a')) setMenuOpen(false); }} aria-label="Primary navigation"><NavLink to="/" end>Home</NavLink><a href="/#training">Services</a><NavLink to="/dog-walking">Dog Walking</NavLink><a href="/#reviews">Reviews</a><NavLink className="nav-account" to="/account">Account</NavLink>{['staff','owner'].includes(user?.role) ? <>{[['schedule', 'Team schedule'], ['people', 'People & access'], ['messages', 'Messages']].map(([tab, label]) => { const current = pathname === '/admin' && (new URLSearchParams(search).get('tab') || 'schedule') === tab; return <Link key={tab} className={`${tab === 'schedule' ? 'nav-book' : ''}${current ? ' active' : ''}`} aria-current={current ? 'page' : undefined} to={`/admin?tab=${tab}`}>{label}</Link>; })}</> : user ? <><NavLink className="nav-book" to="/schedule">My schedule</NavLink><NavLink to="/learn">Member lessons</NavLink><NavLink to="/community?tab=direct">Message Bravo</NavLink></> : <NavLink className="nav-book" to="/portal"><span aria-hidden="true">▣</span> Book a visit</NavLink>}<NotificationBell/>{user && <div className="nav-sign-out"><button type="button" disabled={signingOut} onClick={leave}>{signingOut ? 'Signing out…' : 'Sign out'}</button>{signOutError && <p role="alert">{signOutError}</p>}</div>}</nav></div></header>;
}
export function Footer() { return <footer className="bravo-footer"><div className="shell footer-main"><div><Brand/><p>Professional mobile dog training.<br/>Aberdeen, South Dakota.</p><a className="footer-phone" href="tel:+16058242767">(605) 824-2767</a></div><nav aria-label="Explore Bravo"><h2>Explore</h2><NavLink to="/dog-training">Dog training</NavLink><NavLink to="/behavior-assessment">Behavior assessments</NavLink><NavLink to="/dog-walking">Dog Walking</NavLink><NavLink to="/learn">Online training</NavLink><NavLink to="/community">Member community</NavLink></nav><nav aria-label="Bravo client links"><h2>Stay connected</h2><NavLink to="/account">Your account</NavLink><NavLink to="/community">Message the team</NavLink><NavLink to="/contact">Contact & visit help</NavLink><NavLink to="/accessibility">Accessibility</NavLink><NavLink to="/media-rights">Media permissions</NavLink><a href="/sitemap.xml">Sitemap</a></nav><p className="footer-motto">Trust.<br/>Train.<br/><em>Deploy.</em></p></div><div className="shell footer-baseline footer-baseline--split"><span>© 2026 Bravo K9 Solutions, LLC. All rights reserved.</span><span>ABERDEEN, SD · WE COME TO YOU</span></div><div className="shell footer-credit"><p>Built by Northrop Web Design &amp; Development Team using FRACTURE.</p></div></footer>; }
export function Page({ children, title, eyebrow, intro, className = '' }) { const { pathname } = useLocation(), metadata = PAGE_METADATA[pathname]; return <><Header/><main id="main-content" tabIndex={-1} className={`app-page shell ${className}`}><BackButton/>{metadata && !metadata.private && pathname !== "/" && <nav className="page-breadcrumbs" aria-label="Breadcrumb"><Link to="/">Home</Link><span aria-hidden="true"> / </span><span aria-current="page">{metadata.label}</span></nav>}<div className="app-page-title"><div>{eyebrow && <p className="kicker gold">{eyebrow}</p>}<h1>{title}</h1></div>{intro && <p>{intro}</p>}</div><div className="site-media-tools-slot" data-site-media-tools=""/>{children}</main><Footer/></>; }
export function Notice({ children, error = false }) { return children ? <div className={`notice ${error ? 'notice-error' : ''}`} role={error ? 'alert' : 'status'}>{children}</div> : null; }
export function AppointmentNotice({ compact = false }) { return <aside className={`appointment-policy ${compact ? 'is-compact' : ''}`} aria-label="Important appointment notice"><strong>IMPORTANT APPOINTMENT NOTICE</strong><p>Please provide at least 24 hours’ notice for any appointment changes, cancellations, or rescheduling.</p><p>Changes made with less than 24 hours’ notice are subject to a $100 inconvenience fee.</p></aside>; }
export function SetupNotice() { const { config } = useBravo(); return config && !config.connected ? <Notice>Online accounts and booking are being connected. Browse the programs, or <a href="tel:+16058242767">call (605) 824-2767</a> to arrange care.</Notice> : null; }
export const formatDate = date => new Date(`${date}T12:00:00`).toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
export const formatTime = time => { const h = Number(time.slice(0, 2)); return `${h % 12 || 12}:00 ${h >= 12 ? 'PM' : 'AM'}`; };
