from pathlib import Path
root = Path(__file__).resolve().parents[1]
def edit(name, old, new):
    path = root/name; text = path.read_text()
    if text.count(old) != 1: raise RuntimeError(f'{name}: expected one target for {old[:100]!r}; got {text.count(old)}')
    path.write_text(text.replace(old,new,1))

edit('server/models.js', "export const Settings = model('BravoSettings'", "export const TrainerSchedule = model('BravoTrainerSchedule', new Schema({ _id: String, enabled: Boolean, weekdays: [Number], hours: [String], overrides: [new Schema({ date: String, hours: [String] }, { _id: false })], revision: { type: Number, default: 0 } }, { timestamps: true }));\nexport const Settings = model('BravoSettings'")
edit('server/models.js', 'export const ALL_MODELS = [ChatReset,', 'export const ALL_MODELS = [TrainerSchedule, ChatReset,')
edit('server/app.js', "import { chatFilter, visibleInbox, resetChat } from './chat-state.js';", "import { chatFilter, visibleInbox, resetChat } from './chat-state.js';\nimport { publicTrainerSchedules, readTrainerSchedule, saveTrainerSchedule, checkTrainerVisits } from './trainer-schedules.js';")
edit('server/app.js', "app.use('/api', rateLimit('api', 240, 60000));", "app.use('/api', rateLimit('api', 240, 60000));\napp.get('/api/team/schedules', publicTrainerSchedules);\napp.get('/api/admin/trainer-schedules/:id', requireUser, requireStaff, readTrainerSchedule);\napp.put('/api/admin/trainer-schedules/:id', requireUser, requireStaff, saveTrainerSchedule);")
edit('server/app.js', "getAvailability(String(req.query.from), String(req.query.to))", "getAvailability(String(req.query.from), String(req.query.to), req.query.staffId ? String(req.query.staffId) : null)")
edit('server/app.js', "preference: z.enum(['any', 'morning', 'afternoon', 'evening']), service: z.enum(['training', 'walking', 'aggression'])", "preference: z.enum(['any', 'morning', 'afternoon', 'evening']), service: z.enum(['training', 'walking', 'aggression']), staffId: z.string().regex(/^[a-f\\d]{24}$/i).optional()")
edit('server/app.js', 'getAvailability(input.startDate, input.endDate)', 'getAvailability(input.startDate, input.endDate, input.staffId)')
edit('server/app.js', "    const open = dates.length ? availability({ from: dates[0], to: dates.at(-1), settings }) : [];", "    await checkTrainerVisits(booking.staffId || booking.requestedStaffId, visits, settings, session);\n    const open = dates.length ? availability({ from: dates[0], to: dates.at(-1), settings }) : [];")
edit('server/bookings.js', "import { effectiveServices } from './services.js';", "import { effectiveServices } from './services.js';\nimport { filterTrainerAvailability, checkTrainerVisits } from './trainer-schedules.js';")
edit('server/bookings.js', 'export async function getAvailability(from, to) {', "export async function getAvailability(from, to, staffId = null) {\n  if (staffId) { z.string().regex(/^[a-f\\d]{24}$/i).parse(staffId); await activeTrainer(staffId); }")
edit('server/bookings.js', 'return { days: availability({ from, to, settings, occupied: slots.map(s => s._id) }), enabled: settings.enabled };', 'return { days: await filterTrainerAvailability(availability({ from, to, settings, occupied: slots.map(s => s._id) }), staffId, settings), enabled: settings.enabled };')
edit('server/bookings.js', "      const capacity = data.serviceIds.includes('training')", "      await checkTrainerVisits(chosenTrainerId, data.visits, settings, session);\n      const capacity = data.serviceIds.includes('training')")
edit('server/bookings.js', "  if (!booking.serviceIds?.includes('training')) { booking.staffId = staffId; booking.requestedStaffId ||= staffId; await booking.save(); return booking; }", "  if (!booking.serviceIds?.includes('training')) {\n    await transaction(async session => {\n      const settings = await Settings.findOneAndUpdate({ _id: 'schedule' }, { $inc: { revision: 1 } }, { returnDocument: 'after', session }).lean();\n      await checkTrainerVisits(staffId, booking.visits || [], settings, session);\n      booking.staffId = staffId; booking.requestedStaffId ||= staffId; await booking.save({ session });\n    });\n    return booking;\n  }")
edit('server/bookings.js', '    const capacity = await trainerCapacity(staffId,', '    await checkTrainerVisits(staffId, booking.visits || [], settings, session);\n    const capacity = await trainerCapacity(staffId,')
edit('client/src/Home.tsx', "import Link from './Link';", "import Link from './Link';\nimport TrainerScheduleCard, { useLiveTrainerSchedules } from './TrainerScheduleCard';\nimport './trainer-schedules.css';")
edit('client/src/Home.tsx', '  const { config } = useBravo();', '  const { config } = useBravo();\n  const liveSchedules = useLiveTrainerSchedules();')
edit('client/src/Home.tsx', '<p>{person.bio}</p><Link', '<p>{person.bio}</p><TrainerScheduleCard person={person} live={liveSchedules}/><Link')
edit('client/src/AdminPage.jsx', "import StaffBooking from './StaffBooking';", "import StaffBooking from './StaffBooking';\nimport StaffScheduleEditor from './StaffScheduleEditor';\nimport './trainer-schedules.css';")
edit('client/src/AdminPage.jsx', '<StaffBooking key={`booking-${resetVersion}`} team=', '<StaffScheduleEditor key={`personal-schedule-${resetVersion}`} team={data.team}/><StaffBooking key={`booking-${resetVersion}`} team=')
edit('client/src/AdminPage.jsx', '<summary>Weekly availability & time off</summary>', '<summary>Shared team calendar & closures</summary>')
edit('client/src/BookingPage.jsx', "useState(resume?.trainerId || '')", "useState(resume?.trainerId || (/^[a-f\\d]{24}$/i.test(params.get('trainer') || '') ? params.get('trainer') : ''))")
edit('client/src/BookingPage.jsx', "api(`/availability?from=${from}&to=${to}`)", "api(`/availability?from=${from}&to=${to}${trainerId ? `&staffId=${encodeURIComponent(trainerId)}` : ''}`)")
edit('client/src/BookingPage.jsx', '[from, to, config, availabilityVersion]);', '[from, to, config, availabilityVersion, trainerId]);')
# Keep the same assigned identity when rescheduling an existing request.
edit('client/src/BookingPage.jsx', "setTrainerId(booking.requestedStaffId || booking.staffId || '')", "setTrainerId(booking.staffId || booking.requestedStaffId || '')")
# The assisted-booking UI also filters openings for its chosen trainer.
edit('client/src/StaffBooking.jsx', "import { useState } from 'react';", "import { useEffect, useState } from 'react';")
edit('client/src/StaffBooking.jsx', "  const [service, setService] = useState('training');", "  const [service, setService] = useState('training');\n  const [assignedTrainer, setAssignedTrainer] = useState('');\n  const [loadingSlots, setLoadingSlots] = useState(false);\n  useEffect(() => {\n    let active = true; setSlots([]); setTime('');\n    if (!date) { setLoadingSlots(false); return; }\n    setLoadingSlots(true);\n    api(`/availability?from=${date}&to=${date}${assignedTrainer ? `&staffId=${encodeURIComponent(assignedTrainer)}` : ''}`).then(result => { if (active) setSlots(result.days[0]?.slots || []); }).catch(err => { if (active) setError(err.message); }).finally(() => { if (active) setLoadingSlots(false); });\n    return () => { active = false; };\n  }, [date, assignedTrainer]);")
p=root/'client/src/StaffBooking.jsx'; s=p.read_text(); start=s.index('  async function chooseDate(value) {'); end=s.index('  async function save(e) {',start); s=s[:start]+"  function chooseDate(value) { setDate(value); setError(''); }\n"+s[end:]; s=s.replace('<select name="staffId">','<select name="staffId" value={assignedTrainer} onChange={e => setAssignedTrainer(e.target.value)}>'); s=s.replace("setService('training'); setRequestKey", "setService('training'); setAssignedTrainer(''); setRequestKey"); s=s.replace('disabled={busy || !time}', 'disabled={busy || loadingSlots || !time}'); p.write_text(s)
# New reads in old mocked booking tests must not touch a real database.
p=root/'tests/workspace-api.test.js'; s=p.read_text(); s=s.replace('ALL_MODELS, ChatReset, User,','ALL_MODELS, TrainerSchedule, ChatReset, User,'); old="  t.mock.method(ChatReset, 'find', () => query([]));"; assert s.count(old)==1; s=s.replace(old,old+"\n  t.mock.method(TrainerSchedule, 'findById', () => query(null));"); p.write_text(s)
print('Applied trainer schedule models, public cards, personal editor and booking availability checks.')
