import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {spawnSync} from 'node:child_process';import {routes,programs,people,validateEdits,validatePlan,escapeHTML} from '../public/content.mjs';import {documentHTML} from '../public/pages.mjs';
test('Every route is unique and prerendered with one main element',()=>{assert.equal(new Set(routes).size,routes.length);for(const route of routes){const html=documentHTML(route);assert.equal((html.match(/<main /g)||[]).length,1);assert.match(html,/noindex,nofollow,noarchive/);assert.match(html,/<h1>/);assert.match(html,/No live bookings/);}});
test('All program and trainer detail pages exist',()=>{for(const p of programs)assert.ok(routes.includes('/training/'+p.id));for(const p of people)assert.ok(routes.includes('/team/'+p.id));});
test('Design inputs have a strict allowlist and bounded strings',()=>{assert.deepEqual(validateEdits({gold:'url(javascript:alert(1))',unknown:'x',headline:'A'.repeat(300)}),{});assert.deepEqual(validateEdits({gold:'#BA9A64',headline:'Hello'}),{gold:'#BA9A64',headline:'Hello'});assert.deepEqual(validateEdits(null),{});});
test('Demo choices cannot include customer data or arbitrary destinations',()=>{const p=validatePlan({program:'<script>',trainer:'Unknown',days:['Monday','Monday','https://example.com'],time:'Impossible',email:'private@example.com'});assert.deepEqual(p,{program:'unsure',trainer:'Any trainer',days:['Monday'],time:'Evening'});});
test('All interpolated draft data can be HTML escaped',()=>{assert.equal(escapeHTML('<script>"x"&\''),'&lt;script&gt;&quot;x&quot;&amp;&#39;');});
test('No network calls, production credentials, or live transaction code in application',async()=>{const source=await readFile(new URL('../public/app.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/\bfetch\s*\(|XMLHttpRequest|sendBeacon|WebSocket|MONGODB_URI|STRIPE_SECRET/);});
test('Production deployment build is rejected',()=>{const result=spawnSync(process.execPath,['scripts/build.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,VERCEL_ENV:'production'},encoding:'utf8'});assert.notEqual(result.status,0);assert.match(result.stderr,/STAGING ONLY/);});
test('Production branch build is rejected',()=>{const result=spawnSync(process.execPath,['scripts/build.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,VERCEL_ENV:'preview',VERCEL_GIT_COMMIT_REF:'bravo-mern'},encoding:'utf8'});assert.notEqual(result.status,0);assert.match(result.stderr,/STAGING ONLY/);});
